objects/Api_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Environment_Name__c</fullName>
        <label>Environment Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Api Configuration</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Api Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestApiConfigurationDataController.cls
@IsTest
public class TestApiConfigurationDataController {
    @IsTest
    public static void TestData()
    {
        Api_Configuration__c api= new Api_Configuration__c();
        api.Environment_Name__c='Test';
        api.UserName__c='Test@test.com';
        api.Endpoint_URL__c='http://test.test.com';
        api.Password__c='test';
        insert api;
        Api_Configuration__c obj=ApiConfigurationDataController.RetreiveApiCredentials('Test');
        System.assert(obj!=null);
        
        
    }
  	 @IsTest
    public static void TestData_Nodata()
    {
        Api_Configuration__c obj=ApiConfigurationDataController.RetreiveApiCredentials('Test');
        System.assert(obj==null);
        
        
    }
}