objects/Api_Configuration__c.object
<CustomObject>
    <fields>
        <fullName>Endpoint_URL__c</fullName>
        <label>Endpoint URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Environment_Name__c</fullName>
        <label>Environment Name</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>175</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>UserName__c</fullName>
        <label>UserName</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Api Configuration</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Api Configuration Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Api Configurations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/ApiConfigurationDataController.cls
public class ApiConfigurationDataController {
    
    
    public static Api_Configuration__c RetreiveApiCredentials(string apiEnvName)
    {
        List<Api_Configuration__c> lstDataObj=[Select Endpoint_URL__c ,UserName__c,Password__c,Base_Endpoint__c from Api_Configuration__c where Environment_Name__c=:apiEnvName];
        if(lstDataObj!=null && lstDataObj.size()>0)
        {
            return lstDataObj[0];
        }
        else
        {
            SilverPeakUtils.logException('Could not find the credentials details in Api_Configuration__c object with this name '+ apiEnvName);
        }
        return null;
    }
}