objects/Cap__c.object
<CustomObject>
    <fields>
        <fullName>Account_Name__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account Name</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Cap</relationshipLabel>
        <relationshipName>Caps</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Cap</label>
    <nameField>
        <displayFormat>{YYYY}{MM}{DD}-{0000}</displayFormat>
        <label>Cap Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cap</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/EmailNotificationOnCapCommentsTest.cls
@isTest
public class EmailNotificationOnCapCommentsTest {

    @isTest static void NoCapComments(){
     Account acc  = new Account();
     acc.Name     = 'Hybrid Technologies';
     acc.Type     = 'Prospect'; 
     insert acc;  
     
     Cap__c cap = new Cap__c();
     cap.Account_Name__c = acc.Id;
     cap.Status__c = 'Open';
     cap.Cap_Comments_Recipients__c= 'pmusunuru@silver-peak.com';
     insert cap;
        
     cap.Cap_Comments__c = '';
     update cap;         
    } 
    
    @isTest static void CapCommentsSame(){
     Account acc  = new Account();
     acc.Name     = 'Xyz Technologies';
     acc.Type     = 'Prospect'; 
     insert acc;  
     
     Cap__c cap = new Cap__c();
     cap.Account_Name__c = acc.Id;
     cap.Status__c = 'Open';
     cap.Cap_Comments__c = 'Test Comments';
     cap.Cap_Comments_Recipients__c= 'pmusunuru@silver-peak.com';
     insert cap;
        
     cap.Cap_Comments__c = 'Test Comments';
     update cap;
    }
    
     @isTest static void InvalidEmail(){
     Account acc  = new Account();
     acc.Name     = 'abc Technologies';
     acc.Type     = 'Prospect'; 
     insert acc;  
     
     Cap__c cap = new Cap__c();
     cap.Account_Name__c = acc.Id;
     cap.Status__c = 'Open';
     cap.Cap_Comments__c = 'Test Comments';
     cap.Cap_Comments_Recipients__c= '<pmusunuru@silver-peak.com>,<musunuru.p@gmailcom>';
     insert cap;
        
     cap.Cap_Comments__c = 'Test Comments.Plz Ignore!';
      
         try{
              update cap;
         }
         catch(Exception e){
            System.assert(e.getMessage().contains('Invalid Email Format. Please check following emails:'));
         }
    } 
    
     @isTest static void ValidEmail(){
     Account acc  = new Account();
     acc.Name     = 'Red Technologies';
     acc.Type     = 'Prospect'; 
     insert acc;  
     
     Cap__c cap = new Cap__c();
     cap.Account_Name__c = acc.Id;
     cap.Status__c = 'Open';
     cap.Cap_Comments__c = 'Test Comments';
     cap.Cap_Comments_Recipients__c= '<pmusunuru@silver-peak.com> , <musunuru.p@gmail.com> ';
     insert cap;
        
     cap.Cap_Comments__c = 'Test Comments. Plz Ignore!';
     update cap;
    }
    
    
}