objects/Information_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Information Cards</relationshipLabel>
        <relationshipName>Info_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recalled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No Change</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Merged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Child Account Created</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Information Card</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Info Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Information Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InformationCardControllerTest.cls
@isTest
public class InformationCardControllerTest {
    @isTest
    static void testInformationCard()
    {
        Account acct = new Account(Name='testAcct');
        insert acct;
        Information_Card__c card = new Information_Card__c(Account__c=acct.Id, Status__c = 'New');
        insert card;
        ApexPages.currentPage().getparameters().put('id', card.Id);
        ApexPages.StandardController controller = new ApexPages.StandardController(card);
        InformationCardController ic = new InformationCardController(controller);
    }
}