objects/Information_Card__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Information Cards</relationshipLabel>
        <relationshipName>Info_Cards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Are_you_an_authorized_partner_of__c</fullName>
        <label>Are you an authorized partner of:</label>
        <picklist>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Billing_City__c</fullName>
        <label>Billing City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Country__c</fullName>
        <label>Billing Country</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Postal_Code__c</fullName>
        <label>Billing Postal Code</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_State__c</fullName>
        <label>Billing State</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Billing_Street__c</fullName>
        <label>Billing Street</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Distributor_of_Choice__c</fullName>
        <label>Distributor of Choice</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Domain_Used__c</fullName>
        <label>Email Domain Used</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Integrate_Cloud_Solutions_with_Vendors__c</fullName>
        <label>Integrate Cloud Solutions with Vendors?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MarketingPartnerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Marketing Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Information Cards (Marketing Partner Contact)</relationshipLabel>
        <relationshipName>Information_Cards2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Marketing_Offerings__c</fullName>
        <label>Marketing Offerings</label>
        <picklist>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Number_of_employees_in_your_organization__c</fullName>
        <label>Number of employees in your organization</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_sales_professionals_in_org__c</fullName>
        <label>Professionals in org Outside Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Own_brand_of_professional_services__c</fullName>
        <label>Own brand of professional services?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Please_Name_the_Vendors__c</fullName>
        <label>Please Name the Vendors</label>
        <picklist>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>PrimaryPartnerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Information Cards (Primary Partner Contact)</relationshipLabel>
        <relationshipName>Information_Cards1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_target_market_size__c</fullName>
        <label>Primary target market size?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Professionals_in_org__c</fullName>
        <label>Professionals in org Sales Engineers</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Professionals_in_your_org_Inside_Sales__c</fullName>
        <label>Professionals in org Inside Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Provide_technical_support__c</fullName>
        <label>Provide technical support?</label>
        <picklist>
            <picklistValues>
                <fullName>Not Applicable</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RegisteringUserContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registering User Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Information Cards (Registering User Contact)</relationshipLabel>
        <relationshipName>Information_Cards3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SignatoryPartnerContact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Signatory Partner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Information Cards</relationshipLabel>
        <relationshipName>Information_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Silver_Peak_opportunity_pending__c</fullName>
        <label>Silver Peak opportunity pending</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TOP_3_industries__c</fullName>
        <label>TOP 3 industries</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Tax_ID_Number__c</fullName>
        <label>Tax ID Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Total_annual_sales_revenues_last_year__c</fullName>
        <label>Total annual sales revenues last year?</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Years_in_Business__c</fullName>
        <label>Years in Business</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>business_is_Consulting_Sales__c</fullName>
        <label>% business is Consulting Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>business_is_Product_Sales__c</fullName>
        <label>% business is Product Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>business_is_Services_Sales__c</fullName>
        <label>% business is Services Sales</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Information Card</label>
    <nameField>
        <displayFormat>IC-{000000}</displayFormat>
        <label>Info Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Information Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InformationCardController.cls
public class InformationCardController {
    public Information_Card__c card{ get; set; }
    
    public InformationCardController(ApexPages.StandardController controller)
    {
        String cardId = Apexpages.currentPage().getParameters().get('id');
        card = getCard(cardId);    
    }
    
    private Information_Card__c getCard(String cardId)
    {
        List<Information_Card__c> cards = [Select business_is_Consulting_Sales__c, business_is_Product_Sales__c, business_is_Services_Sales__c, Are_you_an_authorized_partner_of__c, 
                Billing_City__c, Billing_Country__c, Billing_Postal_Code__c, Billing_State__c, Billing_Street__c, Company_Name__c, Distributor_of_Choice__c, Email_Domain_Used__c, Integrate_Cloud_Solutions_with_Vendors__c,
                Marketing_Offerings__c, Number_of_employees_in_your_organization__c, Own_brand_of_professional_services__c, Phone__c, Primary_target_market_size__c, Professionals_in_your_org_Inside_Sales__c,
                Number_of_sales_professionals_in_org__c, Professionals_in_org__c, Provide_technical_support__c, Region__c, Silver_Peak_opportunity_pending__c, Tax_ID_Number__c, 
                TOP_3_industries__c, total_annual_sales_revenues_last_year__c, Website__c, Years_in_Business__c, MarketingPartnerContact__c, PrimaryPartnerContact__c, Please_Name_the_Vendors__c,
                RegisteringUserContact__c, SignatoryPartnerContact__c, Account__r.business_is_Consulting_Sales__c, Account__r.business_is_Product_Sales__c, Account__r.business_is_Services_Sales__c, Account__r.Parent_Company__c, Account__r.Are_you_an_authorized_partner_of__c, 
                Account__r.BillingCity, Account__r.BillingCountry, Account__r.BillingPostalCode, Account__r.BillingState, Account__r.BillingStreet, Account__r.Name, Account__r.Distributor_of_Choice__c, Account__r.Email_Domain_Used__c, Account__r.Integrate_cloudsolutions_with_vendors__c,
                Account__r.Marketting_Oferrings__c, Account__r.Number_of_employees_in_your_organization__c, Account__r.Own_brand_of_professional_services__c, Account__r.Phone, Account__r.Primary_target_market_size__c, Account__r.Professionals_in_your_org_Inside_Sales__c,
                Account__r.Number_of_sales_professionals_in_org__c, Account__r.Professionals_in_org__c, Account__r.Provide_technical_support__c, Account__r.Region__c, Account__r.Silver_Peak_oppo_pend__c, Account__r.Tax_ID_Number__c, 
                Account__r.TOP_3_industries__c, Account__r.total_annual_sales_revenues_last_year__c, Account__r.Website, Account__r.Years_in_Business__c, Account__r.MarketingPartnerContact__c, Account__r.PrimaryPartnerContact__c, Account__r.Please_Name_the_Vendors__c,  
                Account__r.RegisteringUserContact__c, Account__r.SignatoryPartnerContact__c from Information_Card__c where Id =: cardId limit 1];
        if(!cards.isEmpty())
        {
            return cards[0];
        }
        return null;
    }
}