objects/License__c.object
<CustomObject>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Actual_Ship_Date__c</fullName>
        <label>Actual Ship Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EvaluationProductHypervisor__c</fullName>
        <label>Evaluation Product Hypervisor</label>
        <picklist>
            <picklistValues>
                <fullName>VMWare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microsoft Hyper V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Citrix Xen</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>KVM</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Evaluation_Product_1__c</fullName>
        <label>Evaluation Product 1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10 on GX-V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 1700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 2700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 3700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 5700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 7700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 8700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 9700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Evaluation_Product_2__c</fullName>
        <label>Evaluation Product 2</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10 on GX-V</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 1700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 2700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 3700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 5700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 7700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 8700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NX 9700</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>GMS_Needed__c</fullName>
        <label>GMS Ship To</label>
        <picklist>
            <picklistValues>
                <fullName>None Req&apos;d</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Virtual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Site2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Term +Orch-SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Metered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Metered +Orch-SP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Quantity_Location_1__c</fullName>
        <label>Quantity - Location 1</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quantity_Location_2__c</fullName>
        <label>Quantity - Location 2</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped- Pending Extension Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <inlineHelpText>This is the date the POC request is approved to run to</inlineHelpText>
        <label>POC Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VirtualProduct1__c</fullName>
        <label>Virtual Product1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unity Cloud Intelligence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VirtualProduct2__c</fullName>
        <label>Virtual Product2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VirtualProduct3__c</fullName>
        <label>Virtual Product3</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VirtualProduct4__c</fullName>
        <label>Virtual Product4</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VirtualProduct5__c</fullName>
        <label>Virtual Product5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity1__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Virtual Quantity1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity2__c</fullName>
        <label>Virtual Quantity2</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity3__c</fullName>
        <label>Virtual Quantity3</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity4__c</fullName>
        <label>Virtual Quantity4</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity5__c</fullName>
        <label>Virtual Quantity5</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/AutomatePOCRenewalExtensions.cls
public class AutomatePOCRenewalExtensions implements Schedulable, Database.Batchable<sObject>, Database.Stateful
{
    public List<License__c> gmsLicenseIds;
    public AutomatePOCRenewalExtensions() 
    {
        gmsLicenseIds= new List<License__c>();  
    }
    public void execute(SchedulableContext context)
    {
        Database.executeBatch(new AutomatePOCRenewalExtensions(), 10);
    }
    
    public Database.QueryLocator start(Database.BatchableContext context)
    {
        return Database.getQueryLocator([Select Id,Opportunity__c, Opportunity__r.AccountId,POC_Type__c, POC_Contact__c, GMS_Needed__c, EvaluationProductHypervisor__c, Evaluation_Product_1__c, Evaluation_Product_2__c, Quantity_Location_1__c, Quantity_Location_2__c, Status__c, Actual_Ship_Date__c, Target_End_Date__c, VirtualProduct1__c, VirtualProduct2__c, VirtualProduct3__c, VirtualProduct4__c, VirtualProduct5__c, VirtualQuantity1__c, VirtualQuantity2__c, VirtualQuantity3__c, VirtualQuantity4__c, VirtualQuantity5__c  from Request__c where Id in (Select POCRequest__c from Asset where POCREquest__c!=null and Is_Asset_Eligible_For_POC_Renewal_Ext__c=true )]);
    }
    
    public void execute(Database.BatchableContext context, List<sObject> scope)
    {
        List<Request__c> lstReq=(List<Request__c>)scope;
        List<License__c> licenseIds= new List<License__c>();
        List<License__c> virlicenseIds= new List<License__c>();
        List<Id> virIds= new List<Id>();
        for(Request__c pocReq: lstReq)
        {
            SavePoint sp= Database.setSavepoint();
            try
            {
                List<Asset> lstAssetsForRenewal=[Select Id, Name,License_End_Date__c,Renewal_Nodes__c,Product2.Name,Status,Ship_Date__c, Product2.Product_Category__c,Product2.NumberOfLicenses__c,Hosted_GMS__c,GMS_Nodes__c,Product2.Model__c,Renewal_Date__c,Licenses_Nodes__c,Bandwidth_Nodes__c from Asset where  POCRequest__c=:pocReq.Id and Product2.Family='Virtual Image' and Status='Customer Evaluation'];
                List<Asset> assets= new List<Asset>();
                List<Asset> ecOrchAsset= new List<Asset>();
                
                for(Asset item: lstAssetsForRenewal)
                {
                    item.Renewal_Date__c=pocReq.Target_End_Date__c;
                    if(item.Product2.Name.startsWith('EC-BASE')||item.Product2.Name.startsWith('EC-PLUS'))
                    {
                        item.Renewal_Nodes__c=item.Licenses_Nodes__c;
                    }
                    if(item.Product2.Name.startsWith('EC-BOOST'))
                    {
                        item.Renewal_Nodes__c= item.Bandwidth_Nodes__c;
                    }
                    if(item.Product2.Name=='EC-ORCH' || item.Product2.Model__c=='GX-V' || item.Product2.Product_Category__c == 'GMS')
                    {
                        ecOrchAsset.add(item);
                    }
                    else
                    {
                        assets.add(item);
                    }
                }
                if(pocReq.POC_Type__c=='WAN Op')
                {
                    virlicenseIds.addAll(RenewalAssetsHelper.CreateNewLicensesForBatch(assets));
                }
                else if(pocReq.POC_Type__c=='EdgeConnect' || pocReq.POC_Type__c=='Service Provider' || pocReq.POC_Type__c=='EC-SP-Term'||pocReq.POC_Type__c=='EC-SP-Term +Orch-SP'|| pocReq.POC_Type__c=='Perpetual'|| pocReq.POC_Type__c=='EC-SP-Metered'||pocReq.POC_Type__c=='Perpetual-Orchestrator SP'||pocReq.POC_Type__c=='EC-SP-Metered +Orch-SP')
                {
                    RenewalAssetsHelper.RenewEdgeConnectLicense(assets);
                }
                if(ecOrchAsset.size()>0)
                {
                    gmsLicenseIds.addAll(RenewalAssetsHelper.CreateNewLicensesForBatch(ecOrchAsset));
                }
                RenewalAssetsHelper.SendEmailsForPOCRequest(pocReq);
                RenewalAssetsHelper.ClearRenewalDate(assets);
                RenewalAssetsHelper.ClearRenewalDate(ecOrchAsset);
            }
            catch(Exception ex)
            {
                Database.Rollback(sp);
                SilverPEakUtils.logException(ex);
            }   
            
        }
        if(virlicenseIds.size()>0)
        {
            for(License__c item:virlicenseIds)
            {
                virIds.add(item.id);
            }
            if(!Test.isRunningTest())
            {
                AutomatePOCShipmentHelper.encryptLicenses(virIds);
            }
        }
        
    }
    
    public void finish(Database.BatchableContext context)
    {
        if(!Test.isRunningTest())
        {
            List<Id> gmsIds= new List<Id>();
            if(gmsLicenseIds.size()>0)
            {
                for(License__c item:gmsLicenseIds)
                {
                    gmsIds.add(item.id);
                }
                AutomatePOCShipmentHelper.encryptLicenses(gmsIds);
            }
            
            AutomatePOCRenewalExtensions obj= new AutomatePOCRenewalExtensions();
            System.scheduleBatch(obj, 'Automate POC Renewals', 60, 1);
        }
    }
    
}