objects/License__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <formula>AssetId__r.AccountId</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Account ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Asset_Status__c</fullName>
        <formula>TEXT(AssetId__r.Status)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Asset Status</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiration__c</fullName>
        <label>License Expiration</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Quote_Type__c</fullName>
        <formula>AssetId__r.Product_Quote_Type__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Quote Type</label>
        <type>Text</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>license Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/LicenseTriggerHandler.cls
public class LicenseTriggerHandler implements ITriggerHandler {
    public LicenseTriggerHandler()
    {
        
    }
    
    public Boolean IsDisabled()
    {
        return false;
    }
    public void BeforeInsert(List<SObject> newItems) 
    {
        
        if(newItems!=null && newItems.size()>0)
        {
            
        }
        
    }
    public void BeforeUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {
        
        if(newItems!=null && newItems.size()>0)
        {
            
            for (Id licId : newItems.keyset())
            {
                License__c  newLicense=(License__c )newItems.get(licId);
                License__c  oldLicense=(License__c )oldItems.get(licId);
                
                
                
            }
        }
    }
    public void BeforeDelete(Map<Id,SObject> oldItems) 
    {
        
    }
    public void AfterInsert(Map<Id, SObject> newItems) 
    {
        List<Account> lstAccount= new List<Account>();
        if(newItems!=null && newItems.size()>0)
        {
            for(Id licId: newItems.keyset())
            {
                License__c newLic= (License__c)newItems.get(licId);
                if(newLic.License_Expiration__c!=null && newLic.Quote_Type__c=='EDGECONNECT' && (newLic.Model__c != null && newLic.Model__c.startsWith('ECBASE')) && newLic.Asset_Status__c!='Customer Evaluation')
                {
                    lstAccount.add(new Account(Id=newLic.AccountId__c,EC_End_Date__c=newLic.License_Expiration__c));
                }
            }
            if(lstAccount.size()>0)
            {
                update lstAccount;
            }
        }
    }
    public void AfterUpdate(Map<Id, SObject> newItems, Map<Id, SObject> oldItems) 
    {     
        List<Account> lstAccount= new List<Account>();
        if(newItems!=null && newItems.size()>0)
        {
            for (Id licId : newItems.keyset())
            {
                License__c  newLic= (License__c )newItems.get(licId);
                License__c  oldLic= (License__c )oldItems.get(licId);
                if(oldLic.License_Expiration__c!=newLic.License_Expiration__c)
                {
                    if(newLic.Quote_Type__c=='EDGECONNECT' && (newLic.Model__c != null && newLic.Model__c.startsWith('ECBASE')) && newLic.Asset_Status__c!='Customer Evaluation')
                    {
                        lstAccount.add(new Account(Id=newLic.AccountId__c,EC_End_Date__c=newLic.License_Expiration__c));
                    }
                }
            }
            if(lstAccount.size()>0)
            {
                update lstAccount;
            }
        }
        
    }
    public void AfterDelete(Map<Id, SObject> oldItems) 
    {
        
    }
    public void AfterUndelete(Map<Id, SObject> newItems) 
    {
       
    }
}