objects/LMS_Course__c.object
<CustomObject>
    <fields>
        <fullName>Course_Id__c</fullName>
        <label>Course Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Course_Name__c</fullName>
        <label>Course Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Name__c</fullName>
        <label>Display Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>New_Course_Id__c</fullName>
        <label>New Course Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>LMS Course</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMS Courses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Partner_Contact_Profile__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Partner Contacts Profile</relationshipLabel>
        <relationshipName>Partner_Contacts_Profile</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Partner Contact Profile</label>
    <nameField>
        <label>Partner Contact Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Contacts Profile</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestHLMSFetchCertificationsBatch.cls
@Istest
public class TestHLMSFetchCertificationsBatch {
 @IsTest
    public static void TestBatch_email()
    {
        Account testAccount = new Account(Name='acme');
        insert testAccount;
        Contact testContact = new Contact(LastName='acme', AccountId=testAccount.Id,Email='srussell@silver-peak.com');
        insert testContact;
        
        LMS_Course__c course= new LMS_Course__c(Course_Id__c='138078',Course_Name__c='Test Course',Display_Name__c='Test Course Display Name',Is_Active__c=true,New_Course_Id__c='01I38000000RCsf');
        insert course;
        Test.setMock(HttpCalloutMock.class, new HLMSPartnerPortalAPiMock(200, 'OK', 'String body', new Map<String, String> ()));
        Test.startTest();
        H_LMSFetchCertificationsBatch  obj= new H_LMSFetchCertificationsBatch();
        Database.executeBatch(obj);
        Test.stopTest();
    }
    
    @IsTest
    public static void TestBatch_studentId()
    {
        Account testAccount = new Account(Name='acme');
        insert testAccount;
        Contact testContact = new Contact(LastName='acme', AccountId=testAccount.Id,Email='srussell@silver-peak.com',LMS_User_Id__c='01p3B000000Ea8s');
        insert testContact;
        Partner_Contact_Profile__c pc= new Partner_Contact_Profile__c(Contact__c=testContact.Id);
        insert pc;
        
        LMS_Course__c course= new LMS_Course__c(Course_Id__c='138078',Course_Name__c='Test Course',Display_Name__c='Test Course Display Name',Is_Active__c=true,New_Course_Id__c='01I38000000RCsf');
        insert course;
        Test.setMock(HttpCalloutMock.class, new HLMSPartnerPortalAPiMock(200, 'OK', 'String body', new Map<String, String> ()));
        Test.startTest();
        H_LMSFetchCertificationsBatch obj= new H_LMSFetchCertificationsBatch();
        Database.executeBatch(obj);
        AssociateLMSCertificateWithContact objContact= new AssociateLMSCertificateWithContact();
        objContact.execute(null);
        Test.stopTest();
    }
    
    @IsTest
    public static void TestBatch_studentemail()
    {
        Account testAccount = new Account(Name='acme');
        insert testAccount;
        Contact testContact = new Contact(LastName='acme', AccountId=testAccount.Id,Email='srussell@silver-peak.com');
        insert testContact;
        
        
        LMS_Course__c course= new LMS_Course__c(Course_Id__c='138078',Course_Name__c='Test Course',Display_Name__c='Test Course Display Name',Is_Active__c=true,New_Course_Id__c='01I38000000RCsf');
        insert course;
        Test.setMock(HttpCalloutMock.class, new HLMSPartnerPortalAPiMock(200, 'OK', 'String body', new Map<String, String> ()));
        Test.startTest();
        H_LMSFetchCertificationsBatch obj= new H_LMSFetchCertificationsBatch();
        Database.executeBatch(obj);
        AssociateLMSCertificateWithContact objContact= new AssociateLMSCertificateWithContact();
        objContact.execute(null);
        Test.stopTest();
    }
}