objects/LMS_Course_Certification__c.object
<CustomObject>
    <fields>
        <fullName>IsActive__c</fullName>
        <defaultValue>true</defaultValue>
        <label>IsActive</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LMS_User_Id__c</fullName>
        <label>LMS User Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Learner_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Learner Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Certifications</relationshipLabel>
        <relationshipName>Certifications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Student_Email__c</fullName>
        <label>Student Email</label>
        <type>Email</type>
    </fields>
    <label>LMS Course Certification</label>
    <nameField>
        <displayFormat>CRT-{0000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>LMS Certifications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/AssociateLMSCertificateWithContact.cls
public class AssociateLMSCertificateWithContact implements Schedulable {
    
    public void execute(SchedulableContext sc)
    {
        List<LMS_Course_Certification__c> lstCerts=[Select Id,LMS_User_Id__c,Student_Email__c from  LMS_Course_Certification__c where (LMS_User_Id__c!=null or Student_Email__c!=null) and Learner_Contact__c=null and IsActive__c=true];
        List<LMS_Course_Certification__c> lstCertStudentId= new List<LMS_Course_Certification__c>();
        List<LMS_Course_Certification__c> lstCertStudentEmail= new List<LMS_Course_Certification__c>();
        if(lstCerts!=null && lstCerts.size()>0)
        {
            
            for(LMS_Course_Certification__c cert:lstCerts)
            {
                if(cert.LMS_User_Id__c!=null)
                {
                    lstCertStudentId.add(cert);
                }
                if(cert.Student_Email__c!=null)
                {
                    lstCertStudentEmail.add(cert);
                }
            }
            // Associate Certification with Contact
            LMSBatchHelper.H_AssociateContactUsingUserId(lstCertStudentId);
            // Associate Certiifcation with Email Address.
            LMSBatchHelper.H_AssociateContactUsingEmailAddress(lstCertStudentEmail);
            
        }
        
    }
}