objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Activity_Complete__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Client to check the checkbox in community after the activity date</inlineHelpText>
        <label>Activity Complete</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Activity_Date__c</fullName>
        <inlineHelpText>Use: xx/xx/xxxx date format or the date picker</inlineHelpText>
        <label>Activity Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Approval_Status_Hidden__c</fullName>
        <inlineHelpText>Field for MDF Approval Process</inlineHelpText>
        <label>Approval Status (Hidden)</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approval 6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Unsubmitted</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If client doesn&apos;t have a community login (not record owner), populate contact so that he/she can get the emails.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funding Requests (Contact)</relationshipLabel>
        <relationshipName>Funding_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Estimated_Silver_Peak_Amount__c</fullName>
        <label>Estimated Silver Peak Amount</label>
        <precision>12</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MDF_Status__c</fullName>
        <label>MDF Status</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Past Due</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Results</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Planned</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Purchasing_Request__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Purchasing Request</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Purchasing_Request__c.RecordTypeId</field>
                <operation>equals</operation>
                <value>MDF Request</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Purchasing_Request__c</referenceTo>
        <relationshipName>MDF_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SendReminder__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>A time-dependent workflow to check this checkbox and send alert email to client to remind them filling up the post activity information (one day after activity date)</inlineHelpText>
        <label>Send Reminder</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type_of_Program__c</fullName>
        <label>Type of Program</label>
        <picklist>
            <picklistValues>
                <fullName>Awareness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demand Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/Purchase_Request_Lines__c.object
<CustomObject>
    <fields>
        <fullName>Purchasing_Request__c</fullName>
        <label>Purchasing Request</label>
        <referenceTo>Purchasing_Request__c</referenceTo>
        <relationshipLabel>Purchase Request Lines</relationshipLabel>
        <relationshipName>Purchase_Request_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Purchase Request Line</label>
    <nameField>
        <displayFormat>PRL-{00000}</displayFormat>
        <label>PR Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Request Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Purchasing_Request__c.object
<CustomObject>
    <fields>
        <fullName>Approval_Status__c</fullName>
        <label>Approval Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Budget Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Final Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>First_Approver__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>Chosen approver on web submission</inlineHelpText>
        <label>First Approver</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>User.PR_Approver__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Purchasing_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Purchasing Request</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>PR Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchasing Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/TestMDFTriggerHandler.cls
@IsTest
public class TestMDFTriggerHandler {
  @isTest
    static void testCopyMdfToAccount()
    {
        Account acc = new Account(Name='acme');
        insert acc;
        MDF_Request__c mdf = new MDF_Request__c(Account__c=acc.Id, Estimated_Silver_Peak_Amount__c=1000);
        insert mdf;
        
        acc = [select Id, Total_Requested_MDF__c from Account where Id=:acc.Id limit 1];
        System.assertEquals(1000, acc.Total_Requested_MDF__c);
    }
    
    @isTest
    static void testUpdateMdfStatusFromPR()
    {
        List<User> prApprovers = [select Id from User where PR_Approver__c=true limit 1];
        List<RecordType> mdfRecordType = [select Id from RecordType where Name='MDF Request' and SObjectType='Purchasing_Request__c' limit 1];
        Purchasing_Request__c pr = new Purchasing_Request__c(First_Approver__c=prApprovers[0].Id, RecordTypeId=mdfRecordType[0].Id);
        insert pr;
        MDF_Request__c mdf = new MDF_Request__c(Purchasing_Request__c=pr.Id);
        insert mdf;
        
        pr.Approval_Status__c = 'Final Approval';
        update pr;
        mdf = [select Id, Approval_Status__c from MDF_Request__c where Id=:mdf.Id limit 1];
        System.assertEquals('Approved', mdf.Approval_Status__c);
    }
     @isTest
    static void testSubmitPurchaseRequestOnMdfApproval()
    {
        List<RecordType> purchaseRecordType = [select Id from RecordType where SobjectType='Purchasing_Request__c' and Name='MDF Request' limit 1];
        Purchasing_Request__c purchase = new Purchasing_Request__c();
        purchase.RecordTypeId = (purchaseRecordType.size() > 0) ? purchaseRecordType[0].Id : null;
        insert purchase;
        
        MDF_Request__c request = new MDF_Request__c(Purchasing_Request__c=purchase.Id);
        insert request;
        
        request.Approval_Status__c = 'Approved';
        request.Approval_Status_Hidden__c = 'Approved';
        try
        {
            update request;
        }
        catch(Exception ex) {}
    }
    
    @isTest
    static void testMDFShare()
    {
        User portalUser = [select COntactId, COntact.AccountId from User where IsActive = true and UserType = 'PowerPartner' limit 1];
        MDF_Request__c mdf = new MDF_Request__c(Account__c = portalUser.Contact.AccountId);
        MDF_Request__c mdf2 = new MDF_Request__c(Account__c = portalUser.Contact.AccountId);
        insert new List<MDF_Request__c> {mdf, mdf2};
        mdf.Account__c = null;
        update mdf;
        ShareMDFToPartnerHelper.shareMDFs(new List<MDF_Request__c> {mdf, mdf2});
    }
    
    @isTest
    static void testMDFShareSchedule()
    {
        Test.startTest();
        ShareMDFToPartnerSchedule schedulable = new ShareMDFToPartnerSchedule();
        SchedulableContext ctx;
        schedulable.execute(ctx);
        Test.stopTest();
    }
    
    @isTest
    static void testMDFShareBatch()
    {
        Test.startTest();
        String soql = 'select Id, Account__c, OwnerId from MDF_Request__c where Account__c != null limit 1';
        ShareMDFToPartnerBatch currentBatchJob = new ShareMDFToPartnerBatch(soql);
        Database.executeBatch(currentBatchJob, 1);
        Test.stopTest();
    }
     @isTest
    static void testSubmitPurchaseRequestOnMdfApproval1()
    {
        List<RecordType> purchaseRecordType = [select Id from RecordType where SobjectType='Purchasing_Request__c' and Name='MDF Request' limit 1];
        Purchasing_Request__c purchase = new Purchasing_Request__c(First_Approver__c = UserInfo.getUserId());
        purchase.RecordTypeId = (purchaseRecordType.size() > 0) ? purchaseRecordType[0].Id : null;
        insert purchase;
        Purchase_Request_Lines__c  prl = new Purchase_Request_Lines__c (Purchasing_Request__c = purchase.Id);
        insert prl;
        
        MDF_Request__c request = new MDF_Request__c(Purchasing_Request__c=purchase.Id);
        insert request;
        
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setObjectId(request.Id);
        Approval.ProcessResult result = Approval.Process(req);
        
        request.Approval_Status_Hidden__c = 'Approved';
        update request;
    }
    
     @isTest(seeAllData=true)
	public static void testSendEmailAndCreateCampaign()
    {
        List<User> currentUser = [Select Id, Profile.Name, Profile.Id, Name from User where Profile.Name != '13g-SP Partner Community' and IsActive = true limit 1];
        if(currentUser.isEmpty())
        {
            return;
        }
        Contact con = new Contact(LastName='Acme', Email='acme@test.com',FirstName='Acme');
        insert con;
        MDF_Request__c mdf = new MDF_Request__c(Type_of_Program__c ='Awareness', OwnerId = currentUser[0].Id, Contact__c = con.Id, Activity_Date__c = date.today());
        insert mdf;
        MDF_Request__c newMDF = [Select Id, Approval_status__c,Activity_Complete__c, MDF_Status__c, SendReminder__c from MDF_Request__c where Id =: mdf.Id];
        newMDF.Approval_Status__c = 'Approved';
        newMDF.Activity_Complete__c = false;
        newMDF.MDF_Status__c = 'Past Due';
        newMDF.SendReminder__c = true;
		Test.startTest();
        update newMDF;
        Test.stopTest();
		mdf = [Select Id, Campaign__c from MDF_Request__c where Id =: newMDF.Id];
		system.assertEquals(1, [Select Count() from Campaign where Id =: mdf.Campaign__c]);
    }
}