objects/MDF_Request__c.object
<CustomObject>
    <description>This is used for partner portal to build a MDF request and display back to the users in the portal</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>If client doesn&apos;t have a community login (not record owner), populate contact so that he/she can get the emails.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Funding Requests (Contact)</relationshipLabel>
        <relationshipName>Funding_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Event_Materials_Requested__c</fullName>
        <label>Event Materials Requested</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Silver_Peak_Speaking_Opportunity__c</fullName>
        <label>Silver Peak Speaking Opportunity</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type_of_Program__c</fullName>
        <label>Type of Program</label>
        <picklist>
            <picklistValues>
                <fullName>Awareness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demand Generation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enablement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engagement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alignment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Funding Requests</label>
    <nameField>
        <displayFormat>MFR-{0000}</displayFormat>
        <label>Request Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Funding Requests</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/SendUrlToUserTest.cls
/*
 * Test for the SendUrlToUser
 * 23/8/2016 @Author Daniel Wu
 */
@isTest
public class SendUrlToUserTest {
    @isTest
    public static void testSendUrlToUser()
    {
        List<User> currentUser = [Select Id, Profile.Name, Profile.Id, Name from User where Profile.Name != '13g-SP Partner Community' and IsActive = true limit 1];
        if(currentUser.isEmpty())
        {
            return;
        }
        Contact con = new Contact(LastName='Acme', Email='acme@test.com');
        insert con;
        MDF_Request__c mdf = new MDF_Request__c(Type_of_Program__c ='Awareness', Event_Materials_Requested__c = 'test\r\nmessage',
                                                Silver_Peak_Speaking_Opportunity__c = 'Yes', OwnerId = currentUser[0].Id, Contact__c = con.Id);
        insert mdf;
        ApexPages.currentPage().getParameters().put('id',mdf.id);
        SendUrlToUser sutu = new SendUrlToUser();
        sutu.sendEmailToUser();
        
        MDF_Request__c mdf1 = new MDF_Request__c(Type_of_Program__c ='Awareness', Event_Materials_Requested__c = 'test\r\nmessage',
                                                 Silver_Peak_Speaking_Opportunity__c = 'Yes', OwnerId = currentUser[0].Id);
        insert mdf1;
        ApexPages.currentPage().getParameters().put('id',mdf1.id);
        sutu.sendEmailToUser();
        System.assertEquals(sutu.mdfId, '');
        
        ApexPages.currentPage().getParameters().put('id', 'test');
        sutu.sendEmailToUser();
        System.assertEquals(sutu.mdfId, '');
    }
}