objects/Order_Product_Item__c.object
<CustomObject>
    <description>Item for each Order Product quantity to store information related to specific quantity item.</description>
    <fields>
        <fullName>Order_Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Order Product</label>
        <referenceTo>OrderItem</referenceTo>
        <relationshipLabel>Order Product Items</relationshipLabel>
        <relationshipName>Order_Product_Items</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Part_Number__c</fullName>
        <description>Part number related to order product item.</description>
        <label>Part Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serial_Number__c</fullName>
        <description>Serial number of order product item.</description>
        <label>Serial Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status for order product item.</description>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Customer Evaluation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Conditional PO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Owned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cold Spare</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Silver Peak Inventory</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return – Eval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return – Trade In</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return – Conversion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return – CPO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return – Support</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Write-Off</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Obsolete RMA Unit–Supp Transferred–WO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Converted RMA Unit–Supp Transferred–WO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Demo / NFR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Subscription Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer Subscription Expired</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owned Eval/NFR</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Order Product Item</label>
    <nameField>
        <displayFormat>OPI-{000000}</displayFormat>
        <label>Order Product Item Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Product Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/HardwareShipmentControllerTest.cls
@isTest
private class HardwareShipmentControllerTest {
	
	@TestSetup static void whenCreateTestData(){
		Account spAccount = new Account();
		spAccount.Name = 'Silver Peak Systems';
		insert spAccount;

		Account account = new Account();
		account.Name = 'Test Account';
		insert account;

		Opportunity opportunity = new Opportunity();
		opportunity.Name = 'Test Opportunity';
		opportunity.CloseDate = System.Today();
		opportunity.StageName = 'New';
		opportunity.AccountId = account.Id;
		insert opportunity;

		Order order = new Order();
		order.AccountId = account.Id;
		order.OpportunityId = opportunity.Id;
		order.EffectiveDate = System.today();
		order.Status = 'Draft';
		insert order;
	}

	@isTest static void whenTestWithZeroOrderProducts() {
		Order order = [SELECT Id, SBQQ__Quote__c, Status FROM Order LIMIT 1];

		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', order.id);
			ApexPages.StandardController stdOrder = new ApexPages.StandardController(order);
			HardwareShipmentController controller = new HardwareShipmentController(stdOrder);
			controller.rerenderForm();
			controller.returnToOrder();
			Boolean testBoolean = controller.displayErrorOnly;
			OrderShipmentHelper.getAllOrderFieldsAPINames();
		Test.stopTest();
	}

	@isTest static void whenTestWithOrderProducts(){
		Order order = [SELECT Id, SBQQ__Quote__c FROM Order LIMIT 1];

		Product2 product = new Product2();
		product.Name = 'EC-BASE-2Y';
		product.Family = 'Virtual Image';
		product.ProductCode = '300128-002';
		product.Model__c = 'EC-BASE-2Y';
		product.IsActive = true;
		product.Forecast_Category__c = 'Physical';
		insert product;

        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = product.Id;
        standardPrice.UnitPrice = 1000;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name = 'Custom Pricebook';
        customPB.isActive = true;
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.product2Id = product.Id;
        customPrice.UnitPrice = 2000;
        customPrice.IsActive = true; 
        insert customPrice;

        order.Pricebook2Id = customPB.Id;
        order.Sales_Order_Number__c = 'SO034507';
        update order;

		OrderItem orderProduct = new OrderItem();
		orderProduct.PricebookEntryId = customPrice.Id;
		orderProduct.Product2Id = product.Id;
		orderProduct.Quantity = 1;
		orderProduct.OrderId = order.Id;
		orderProduct.UnitPrice = 1000;
		insert orderProduct;

		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', order.id);
			ApexPages.StandardController stdOrder = new ApexPages.StandardController(order);
			HardwareShipmentController controller = new HardwareShipmentController(stdOrder);

			controller.csvFile.body = Blob.valueOf('No.,SHO,Customer Name,Req#,Request Type,OEM CUST Name,Item#,S/N,LOCID,Location Type,Qty,Shipped Date,Ship Method,Tracking#,Ref PO#,RMA#,RMA Received Date,Contact,Phone Number,Address 1,Address 2,Address 3,City,State/Province,Zip/Postal Code,Country,1,CSHO-99999999,SILVERPEAK,SO034507,SP-SOLD,Blood Systems,300128-002_500190-001,001BBC199D5A,SP-SHIPD-SOLD,VIRTUALPOOL,1,2/13/2018,Test Line,"425428745952, 425428745963, 425428745974, 425428745985, 425428745996, 425428746000, ",PO999999,,,Drew Justus,Test,Test,Test,,Test,n.a,99999,USA');
			controller.applyCSVFile();

			controller.checkSerialNumberStatus();
			controller.copySerialNumberOrderProductId = orderProduct.Id;
			controller.updateCopySerialNumberView();

			controller.csvFile.body = null;
			controller.applyCSVFile();

			controller.save();

		Test.stopTest();
	}

	@isTest static void whenTestWithExistingOrderProductItems(){
		Order order = [SELECT Id, SBQQ__Quote__c FROM Order LIMIT 1];

		Product2 product = new Product2();
		product.Name = 'EC-BASE-2Y';
		product.Family = 'Virtual Image';
		product.ProductCode = '300128-002';
		product.Model__c = 'EC-BASE-2Y';
		product.IsActive = true;
		product.Forecast_Category__c = 'Physical';
		insert product;

        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = product.Id;
        standardPrice.UnitPrice = 1000;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name = 'Custom Pricebook';
        customPB.isActive = true;
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.product2Id = product.Id;
        customPrice.UnitPrice = 2000;
        customPrice.IsActive = true; 
        insert customPrice;

        order.Pricebook2Id = customPB.Id;
        order.Sales_Order_Number__c = 'SO034507';
        update order;

		OrderItem orderProduct = new OrderItem();
		orderProduct.PricebookEntryId = customPrice.Id;
		orderProduct.Product2Id = product.Id;
		orderProduct.Quantity = 1;
		orderProduct.OrderId = order.Id;
		orderProduct.UnitPrice = 1000;
		insert orderProduct;

		Order_Product_Item__c testOrderProductItem = new Order_Product_Item__c();
		testOrderProductItem.Order_Product__c = orderProduct.Id;
		testOrderProductItem.Serial_Number__c = 'testSN';
		testOrderProductItem.Part_Number__c = 'test PN';
		testOrderProductItem.Status__c = 'Customer Owned';
		insert testOrderProductItem;

		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', order.id);
			ApexPages.StandardController stdOrder = new ApexPages.StandardController(order);
			HardwareShipmentController controller = new HardwareShipmentController(stdOrder);

			controller.csvFile.body = Blob.valueOf('No.,SHO,Customer Name,Req#,Request Type,OEM CUST Name,Item#,S/N,LOCID,Location Type,Qty,Shipped Date,Ship Method,Tracking#,Ref PO#,RMA#,RMA Received Date,Contact,Phone Number,Address 1,Address 2,Address 3,City,State/Province,Zip/Postal Code,Country,1,CSHO-99999999,SILVERPEAK,SO034507,SP-SOLD,Blood Systems,300128-002_500190-001,001BBC199D5A,SP-SHIPD-SOLD,VIRTUALPOOL,1,2/13/2018,Test Line,"425428745952, 425428745963, 425428745974, 425428745985, 425428745996, 425428746000, ",PO999999,,,Drew Justus,Test,Test,Test,,Test,n.a,99999,USA');
			controller.applyCSVFile();

			controller.checkSerialNumberStatus();
			controller.copySerialNumberOrderProductId = orderProduct.Id;
			controller.updateCopySerialNumberView();

			controller.save();

			//controller = new HardwareShipmentController(stdOrder);

			// When test OrderShipmentHelper component

			//List<Order_Product_Item__c> existingOrderProductItems = new List<Order_Product_Item__c>();
			
			//Order_Product_Item__c testOrderProductItem = new Order_Product_Item__c();
			//testOrderProductItem.Order_Product__c = orderProduct.Id;
			//testOrderProductItem.Serial_Number__c = 'testSN';
			//insert testOrderProductItem;

			//existingOrderProductItems.add(testOrderProductItem);

			//OrderShipmentHelper.buildOrderProductItemWrappersFromExistingOrderProductItems(existingOrderProductItems);

		Test.stopTest();
	}

	@isTest static void whenTestWithExistingAsset(){
		Order order = [SELECT Id, SBQQ__Quote__c FROM Order LIMIT 1];
		Account account = [SELECT Id FROM Account LIMIT 1];

		Product2 product = new Product2();
		product.Name = 'EC-BASE-2Y';
		product.Family = 'Virtual Image';
		product.ProductCode = '300128-002';
		product.Model__c = 'EC-BASE-2Y';
		product.IsActive = true;
		product.Forecast_Category__c = 'Physical';
		insert product;

		Asset asset = new Asset();
		asset.Name = 'Test HW Product';
		asset.AccountId = account.Id;
		asset.Product2Id = product.Id;
		asset.Quantity = 1;
		asset.SerialNumber = '001BBC199D5A';
		insert asset;

        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = product.Id;
        standardPrice.UnitPrice = 1000;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name = 'Custom Pricebook';
        customPB.isActive = true;
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.product2Id = product.Id;
        customPrice.UnitPrice = 2000;
        customPrice.IsActive = true; 
        insert customPrice;

        order.Pricebook2Id = customPB.Id;
        order.Sales_Order_Number__c = 'SO034507';
        update order;

		OrderItem orderProduct = new OrderItem();
		orderProduct.PricebookEntryId = customPrice.Id;
		orderProduct.Product2Id = product.Id;
		orderProduct.Quantity = 1;
		orderProduct.OrderId = order.Id;
		orderProduct.UnitPrice = 1000;
		insert orderProduct;

		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', order.id);
			ApexPages.StandardController stdOrder = new ApexPages.StandardController(order);
			HardwareShipmentController controller = new HardwareShipmentController(stdOrder);

			controller.csvFile.body = Blob.valueOf('No.,SHO,Customer Name,Req#,Request Type,OEM CUST Name,Item#,S/N,LOCID,Location Type,Qty,Shipped Date,Ship Method,Tracking#,Ref PO#,RMA#,RMA Received Date,Contact,Phone Number,Address 1,Address 2,Address 3,City,State/Province,Zip/Postal Code,Country,1,CSHO-99999999,SILVERPEAK,SO034507,SP-SOLD,Blood Systems,300128-002_500190-001,001BBC199D5A,SP-SHIPD-SOLD,VIRTUALPOOL,1,2/13/2018,Test Line,"425428745952, 425428745963, 425428745974, 425428745985, 425428745996, 425428746000, ",PO999999,,,Drew Justus,Test,Test,Test,,Test,n.a,99999,USA');
			controller.applyCSVFile();

			controller.checkSerialNumberStatus();
			controller.copySerialNumberOrderProductId = orderProduct.Id;
			controller.updateCopySerialNumberView();

			controller.csvFile.body = null;
			controller.applyCSVFile();

			controller.save();

		Test.stopTest();
	}

	@isTest static void whenTestCSVItemsDontMatchNumberOfOrderProducts(){
		Order order = [SELECT Id, SBQQ__Quote__c FROM Order LIMIT 1];

		Product2 product = new Product2();
		product.Name = 'EC-BASE-2Y';
		product.Family = 'Virtual Image';
		product.ProductCode = '300128-002';
		product.Model__c = 'EC-BASE-2Y';
		product.IsActive = true;
		product.Forecast_Category__c = 'Physical';
		insert product;

        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = product.Id;
        standardPrice.UnitPrice = 1000;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name = 'Custom Pricebook';
        customPB.isActive = true;
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.product2Id = product.Id;
        customPrice.UnitPrice = 2000;
        customPrice.IsActive = true; 
        insert customPrice;

        order.Pricebook2Id = customPB.Id;
        order.Sales_Order_Number__c = 'SO034507';
        update order;

		OrderItem orderProduct = new OrderItem();
		orderProduct.PricebookEntryId = customPrice.Id;
		orderProduct.Product2Id = product.Id;
		orderProduct.Quantity = 1;
		orderProduct.OrderId = order.Id;
		orderProduct.UnitPrice = 1000;
		insert orderProduct;

		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', order.id);
			ApexPages.StandardController stdOrder = new ApexPages.StandardController(order);
			HardwareShipmentController controller = new HardwareShipmentController(stdOrder);

			// No matching products
			controller.csvFile.body = Blob.valueOf('No.,SHO,Customer Name,Req#,Request Type,OEM CUST Name,Item#,S/N,LOCID,Location Type,Qty,Shipped Date,Ship Method,Tracking#,Ref PO#,RMA#,RMA Received Date,Contact,Phone Number,Address 1,Address 2,Address 3,City,State/Province,Zip/Postal Code,Country');
			controller.applyCSVFile();

			System.debug('Two matching products');

			// Two matching products
			controller.csvFile.body = Blob.valueOf('No.,SHO,Customer Name,Req#,Request Type,OEM CUST Name,Item#,S/N,LOCID,Location Type,Qty,Shipped Date,Ship Method,Tracking#,Ref PO#,RMA#,RMA Received Date,Contact,Phone Number,Address 1,Address 2,Address 3,City,State/Province,Zip/Postal Code,Country,1,CSHO-99999999,SILVERPEAK,SO034507,SP-SOLD,Blood Systems,300128-002_500190-001,001BBC199D5A,SP-SHIPD-SOLD,VIRTUALPOOL,1,2/13/2018,Test Line,"425428745952, 425428745963, 425428745974, 425428745985, 425428745996, 425428746000, ",PO999999,,,Drew Justus,Test,Test,Test,,Test,n.a,99999,USA,1,CSHO-99999999,SILVERPEAK,SO034507,SP-SOLD,Blood Systems,300128-002_500190-001,001BBC199D5A,SP-SHIPD-SOLD,VIRTUALPOOL,1,2/13/2018,Test Line,"425428745952, 425428745963, 425428745974, 425428745985, 425428745996, 425428746000, ",PO999999,,,Drew Justus,Test,Test,Test,,Test,n.a,99999,USA');
			controller.applyCSVFile();

		Test.stopTest();
	}

	@isTest static void whenTestCSVItemsDontMatchNumberOfOrderProducts2(){
		Order order = [SELECT Id, SBQQ__Quote__c FROM Order LIMIT 1];

		Product2 product = new Product2();
		product.Name = 'EC-BASE-2Y';
		product.Family = 'Virtual Image';
		product.ProductCode = '300128-002';
		product.Model__c = 'EC-BASE-2Y';
		product.IsActive = true;
		product.Forecast_Category__c = 'Physical';
		insert product;

        Id pricebookId = Test.getStandardPricebookId();
        
        // 1. Insert a price book entry for the standard price book.
        // Standard price book entries require the standard price book ID we got earlier.
        PricebookEntry standardPrice = new PricebookEntry();
        standardPrice.Pricebook2Id = pricebookId;
        standardPrice.Product2Id = product.Id;
        standardPrice.UnitPrice = 1000;
        standardPrice.IsActive = true;
        insert standardPrice;
        
        Pricebook2 customPB = new Pricebook2();
        customPB.Name = 'Custom Pricebook';
        customPB.isActive = true;
        insert customPB;
        
        PricebookEntry customPrice = new PricebookEntry();
        customPrice.Pricebook2Id = customPB.Id;
        customPrice.product2Id = product.Id;
        customPrice.UnitPrice = 2000;
        customPrice.IsActive = true; 
        insert customPrice;

        order.Pricebook2Id = customPB.Id;
        order.Sales_Order_Number__c = 'SO034507';
        update order;

		OrderItem orderProduct = new OrderItem();
		orderProduct.PricebookEntryId = customPrice.Id;
		orderProduct.Product2Id = product.Id;
		orderProduct.Quantity = 2;
		orderProduct.OrderId = order.Id;
		orderProduct.UnitPrice = 1000;
		insert orderProduct;

		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', order.id);
			ApexPages.StandardController stdOrder = new ApexPages.StandardController(order);
			HardwareShipmentController controller = new HardwareShipmentController(stdOrder);

			// 1 matching product in file, product quantity 2 on order.
			controller.csvFile.body = Blob.valueOf('No.,SHO,Customer Name,Req#,Request Type,OEM CUST Name,Item#,S/N,LOCID,Location Type,Qty,Shipped Date,Ship Method,Tracking#,Ref PO#,RMA#,RMA Received Date,Contact,Phone Number,Address 1,Address 2,Address 3,City,State/Province,Zip/Postal Code,Country,1,CSHO-99999999,SILVERPEAK,SO034507,SP-SOLD,Blood Systems,300128-002_500190-001,001BBC199D5A,SP-SHIPD-SOLD,VIRTUALPOOL,1,2/13/2018,Test Line,"425428745952, 425428745963, 425428745974, 425428745985, 425428745996, 425428746000, ",PO999999,,,Drew Justus,Test,Test,Test,,Test,n.a,99999,USA');
			controller.applyCSVFile();

		Test.stopTest();
	}

}