objects/Patch__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patch_Name__c</fullName>
        <description>Name Identifer</description>
        <label>Patch Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessingSequence__c</fullName>
        <inlineHelpText>Smaller number gets higher priority</inlineHelpText>
        <label>Processing Sequence</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rule_Logic__c</fullName>
        <inlineHelpText>A formula referencing the processing sequence of criteria rules, indicating the logic of how the rules to be evaluated. e.g. &quot;4&quot;, &quot;1 AND 2&quot;, &quot;2 AND (3 OR 4)&quot;, &quot;2 AND NOT (3 OR 4)&quot;</inlineHelpText>
        <label>Rule Logic</label>
        <length>200</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Named Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GEO Based</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patch</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Patch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PatchCriteriaRule__c.object
<CustomObject>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ends with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in range</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in match list</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Patch__c</fullName>
        <label>Patch</label>
        <referenceTo>Patch__c</referenceTo>
        <relationshipLabel>Patch Criteria Rules</relationshipLabel>
        <relationshipName>Patch_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProcessingSequence__c</fullName>
        <label>Processing Sequence</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Range_High__c</fullName>
        <label>Range High</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Range_Low__c</fullName>
        <label>Range Low</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Domain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Patch Criteria Rule</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Patch Criteria Rule #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patch Criteria Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/PatchMatchList__c.object
<CustomObject>
    <fields>
        <fullName>Patch_Criteria_Rule__c</fullName>
        <label>Patch Criteria Rule</label>
        <referenceTo>PatchCriteriaRule__c</referenceTo>
        <relationshipLabel>Patch Match Lists</relationshipLabel>
        <relationshipName>MatchList</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Patch Match List</label>
    <nameField>
        <label>Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Patch Match Lists</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PatchRuleEngineBuilderTest.cls
@isTest
public class PatchRuleEngineBuilderTest
{
    @isTest
    static void test()
    {
        Patch__c patch1 = new Patch__c(Patch_Name__c='acme', Active__c=true, ProcessingSequence__c=1, Type__c='Named Accounts');
        insert patch1;
        PatchCriteriaRule__c rule11 = new PatchCriteriaRule__c(Patch__c=patch1.Id, Type__c='Country', Operation__c='equals', Value__c='US', ProcessingSequence__c=1);
        insert rule11;
        PatchCriteriaRule__c rule12 = new PatchCriteriaRule__c(Patch__c=patch1.Id, Type__c='Company Name', Operation__c='in match list', Value__c='US', ProcessingSequence__c=2);
        insert rule12;
        PatchMatchList__c match121 = new PatchMatchList__c(Patch_Criteria_Rule__c=rule12.Id, Name='11111');
        insert match121;
        Patch__c patch2 = new Patch__c(Patch_Name__c='acme', Active__c=true, ProcessingSequence__c=2, Rule_Logic__c='1 AND 2 AND 3');
        insert patch2;
        PatchCriteriaRule__c rule21 = new PatchCriteriaRule__c(Patch__c=patch2.Id, Type__c='Country', Operation__c='in', Value__c='US', ProcessingSequence__c=1);
        insert rule21;
        PatchCriteriaRule__c rule22 = new PatchCriteriaRule__c(Patch__c=patch2.Id, Type__c='Zip Code', Operation__c='in range', Range_Low__c='11111', Range_High__c='22222', ProcessingSequence__c=2);
        insert rule22;
        PatchCriteriaRule__c rule23 = new PatchCriteriaRule__c(Patch__c=patch2.Id, Type__c='Zip Code', Operation__c='in match list', ProcessingSequence__c=3);
        insert rule23;
        PatchMatchList__c match231 = new PatchMatchList__c(Patch_Criteria_Rule__c=rule23.Id, Name='11111');
        insert match231;
        
        PatchRuleEngineBuilder builder = new PatchRuleEngineBuilder();
        System.assert(builder.build() != null);
    }
}