objects/Patch__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>CSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>CAM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Catchall__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Catchall</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISR__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ISR</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>IsSalesTeam__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates patch will use Sales Team setting to assign team member instead of patch user settings.</inlineHelpText>
        <label>Sales Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Overlay_1__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Overlay 1</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patches_O1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Overlay_2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Overlay 2</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patches_O2</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patch Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Patch_Name__c</fullName>
        <description>Name Identifer</description>
        <label>Patch Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Named Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GEO Based</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patch</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Patch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesTeam__c.object
<CustomObject>
    <fields>
        <fullName>Patch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patch</label>
        <referenceTo>Patch__c</referenceTo>
        <relationshipLabel>Sales Teams</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Sales Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>RSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Owner</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SalesTeam__c</fullName>
        <label>Sales Team</label>
        <referenceTo>SalesTeam__c</referenceTo>
        <relationshipLabel>Sales Team Members</relationshipLabel>
        <relationshipName>SalesTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Team Members (CAM)</relationshipLabel>
        <relationshipName>SalesTeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Team Member</label>
    <nameField>
        <displayFormat>STM-{0000000}</displayFormat>
        <label>Sales Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PatchOverrideController.cls
/*
 * Controller of page PatchOverride
 */
public with sharing class PatchOverrideController 
{
    private sObject obj;

    public PatchOverrideController()
    {
        Id objId = ApexPages.currentPage().getParameters().get('id');
        IsAllowed = true;
        obj = PatchRuleHelper.getSObject(objId);
        ObjectName = (String)obj.get('Name');
        SegmentationTypeAccount = new Account();
        if(obj != null)
        {
            if((Boolean)obj.get('Patch_Locked__c'))
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Warning, 'Record is locked, you can\'t override the patch'));
                IsAllowed = false;
            }
        }
        else
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Object is not found'));
        }
    }

    public Boolean IsAllowed { get; set; }
    public String CompanyName { get; set; }
    public String EmailDomain { get; set; }
    public String Country { get; set; }
    public String State { get; set; }
    public String ZipCode { get; set; }
    public String Industry { get; set; }
    public Account SegmentationTypeAccount { get; set; }
    public String ObjectName { get; set; }

    public PageReference reassign()
    {
        PatchRuleEngineBase.Target target = getPatchTarget();
        try
        {
            PatchRuleEngine engine = new PatchRuleEngine();
            PatchRuleEngineBase.Match match = engine.match(target);
            Id patchId = match.PatchId;
            PatchRuleHelper.OverlayHolder.put(obj.Id, match.OverlayMatches);
            PatchRuleHelper.OverrideSegmentationType = SegmentationTypeAccount.SegmentationType__c;
            if(patchId == null)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'No match found. Please try with another values.'));
                return null;
            }
            List<Patch__c> patchs = [select Id, IsSalesTeam__c, Patch_Name__c, Catchall__c, Type__c, Owner__c, Owner__r.GEO__c, RSM__c, CSM__c, 
                                            SE__c, ISR__c, Active__c, Overlay_1__c, Overlay_2__c 
                                        from Patch__c where Id=:patchId limit 1];
            if(patchs.size() == 0)
            {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Error occured. Patch Rules need re-deployment'));
                return null;
            }

            if(patchs[0].IsSalesTeam__c)
            {
                Map<String, List<SalesTeamMember__c>> type2membersMap = new Map<String, List<SalesTeamMember__c>>();
                for(SalesTeamMember__c member : [select Id, User__c, Role__c, SalesTeam__r.Type__c, SalesTeam__r.Patch__c 
                                                   from SalesTeamMember__c where SalesTeam__r.Patch__c = :patchId])
                {
                    if(type2membersMap.containsKey(member.SalesTeam__r.Type__c))
                    {
                        type2membersMap.get(member.SalesTeam__r.Type__c).add(member);
                    }
                    else
                    {
                        type2membersMap.put(member.SalesTeam__r.Type__c, new List<SalesTeamMember__c>{ member });
                    }
                }
                PatchRuleHelper.assignPatchBySalesTeams(obj, patchs[0], null, type2membersMap);
            }
            else
            {
                PatchRuleHelper.assignPatch(obj, patchs[0]);
            }
            obj.put('Patch_Locked__c', true);
            update obj;

            PatchRuleHelper.AssignTeamMembers(new List<Id> { obj.Id });
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Patch reassigned.<script>opener.location=\'/'+obj.Id+'\';setTimeout("window.close()", 3000);</script>'));
        }
        catch(Exception ex)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Failed to reassign, the error message is: ' + ex.getMessage()));
        }
        return null;
    }

    private PatchRuleEngineBase.Target getPatchTarget()
    {
        PatchRuleEngineBase.Target target = new PatchRuleEngineBase.Target();
        target.Company = CompanyName;
        target.EmailDomain = PatchRuleHelper.getEmailDomain(EmailDomain);
        target.Country = Country;
        target.ZipCode = ZipCode;
        target.State = State;
        target.Industry = Industry;
        return target;
    }
}