objects/Patch__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patch_Name__c</fullName>
        <description>Name Identifer</description>
        <label>Patch Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessingSequence__c</fullName>
        <inlineHelpText>Smaller number gets higher priority</inlineHelpText>
        <label>Processing Sequence</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Named Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GEO Based</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patch</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Patch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/PatchCriteriaRule__c.object
<CustomObject>
    <fields>
        <fullName>Operation__c</fullName>
        <label>Operation</label>
        <picklist>
            <controllingField>Type__c</controllingField>
            <picklistValues>
                <fullName>equals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>starts with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ends with</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>contains</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in range</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>in match list</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Patch__c</fullName>
        <label>Patch</label>
        <referenceTo>Patch__c</referenceTo>
        <relationshipLabel>Patch Criteria Rules</relationshipLabel>
        <relationshipName>Patch_Rules</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>ProcessingSequence__c</fullName>
        <label>Processing Sequence</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Company Name</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Email Domain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Country</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Zip Code</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>State</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Patch Criteria Rule</label>
    <nameField>
        <displayFormat>R-{00000}</displayFormat>
        <label>Patch Criteria Rule #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patch Criteria Rules</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PatchRealignJobTest.cls
@isTest
public class PatchRealignJobTest
{
    @isTest
    static void test()
    {
        Patch__c patch = new Patch__c(Patch_Name__c='acme', Active__c=true);
        insert patch;
        Lead lead = new Lead(LastName='acme', Company='acme', Patch__c=patch.Id);
        insert lead;
        
        Test.startTest();
        PatchRealignJob job = new PatchRealignJob(new List<Id> {patch.Id});
        Database.executeBatch(job, 1);
        Test.stopTest();
    }  
    
    @isTest(SeeAllData=True)
    static void InReviewAccount()
    {
        Patch__c patch = new Patch__c(Patch_Name__c='acme', Active__c=true);
        insert patch;
        Account acc = new Account(Name='Test InReview Account', Type='In Review');
        insert acc;
        
        Test.startTest();
        PatchRealignJob job = new PatchRealignJob(new List<Id> {patch.Id});
        Database.executeBatch(job, 1);
        Test.stopTest();
        Account acc1= [Select Trigger_Assignment__c, Patch__c from Account where Id =:acc.Id];
        system.assertEquals(False, acc1.Trigger_Assignment__c); 
        system.assertEquals(Null, acc1.Patch__c);
    }
    
    @isTest(SeeAllData=True)
    static void NotInReviewAccount()
    {
        Patch__c patch = new Patch__c(Patch_Name__c='acme', Active__c=true, ProcessingSequence__c=5000);
        insert patch;
        PatchCriteriaRule__c rule1 = new PatchCriteriaRule__c(Patch__c=patch.Id, Type__c='State', Operation__c='equals', Value__c='MLKTest', ProcessingSequence__c=1);
        insert rule1;
        Account acc = new Account(Name='Test InReview Account', Type='Customer', Patch__c=patch.Id);
        insert acc;
        
        Test.startTest();
        PatchRealignJob job = new PatchRealignJob(new List<Id> {patch.Id});
        Database.executeBatch(job, 1);
        Test.stopTest();
        Account acc1= [Select Trigger_Assignment__c, Patch__c from Account where Id =:acc.Id];
        Patch__c p= [Select Id from Patch__c where Name='P-480'];
        system.assertEquals(False, acc1.Trigger_Assignment__c); 
        system.assertEquals(p.Id, acc1.Patch__c);
    }
    
    @isTest(SeeAllData=True)
    static void OpportunityTest()
    {
        Patch__c patch = new Patch__c(Patch_Name__c='acme', Active__c=true, ProcessingSequence__c=5000);
        insert patch;
        PatchCriteriaRule__c rule1 = new PatchCriteriaRule__c(Patch__c=patch.Id, Type__c='State', Operation__c='equals', Value__c='MLKTest', ProcessingSequence__c=1);
        insert rule1;
        Account acc = new Account(Name='Test Account', Type='Customer', Patch__c=patch.Id);
        insert acc;
        Opportunity opp = new Opportunity(Name='Test Opportunity', AccountId=acc.Id,StageName='Discovery', CloseDate=Date.today(), Patch__c=patch.Id);
        insert opp;
        
        Test.startTest();
        PatchRealignJob job = new PatchRealignJob(new List<Id> {patch.Id});
        Database.executeBatch(job, 1);
        Test.stopTest();
        Opportunity o= [Select Patch__c from Opportunity where Id =:opp.Id];
        Patch__c p= [Select Id from Patch__c where Name='P-480'];
        system.assertEquals(p.Id, o.Patch__c);
    }
}