objects/Patch__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>IsSalesTeam__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Indicates patch will use Sales Team setting to assign team member instead of patch user settings.</inlineHelpText>
        <label>Sales Team</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Patch_Name__c</fullName>
        <description>Name Identifer</description>
        <label>Patch Name</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessingSequence__c</fullName>
        <inlineHelpText>Smaller number gets higher priority</inlineHelpText>
        <label>Processing Sequence</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Patch_Assignments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Named Accounts</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GEO Based</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Industry</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Patch</label>
    <nameField>
        <displayFormat>P-{000}</displayFormat>
        <label>Patch Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Patches</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesTeam__c.object
<CustomObject>
    <fields>
        <fullName>Patch__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Patch</label>
        <referenceTo>Patch__c</referenceTo>
        <relationshipLabel>Sales Teams</relationshipLabel>
        <relationshipName>Sales_Teams</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <label>Sales Team</label>
    <nameField>
        <displayFormat>ST-{000000}</displayFormat>
        <label>Sales Team Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/SalesTeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>RSM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ISR</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FCMM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SEM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Team Owner</fullName>
            </picklistValues>
        </picklist>
        <required>true</required>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SalesTeam__c</fullName>
        <label>Sales Team</label>
        <referenceTo>SalesTeam__c</referenceTo>
        <relationshipLabel>Sales Team Members</relationshipLabel>
        <relationshipName>SalesTeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipLabel>Sales Team Members (CAM)</relationshipLabel>
        <relationshipName>SalesTeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Team Member</label>
    <nameField>
        <displayFormat>STM-{0000000}</displayFormat>
        <label>Sales Team Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/PatchUserReplaceControllerTest.cls
@isTest
public class PatchUserReplaceControllerTest
{
    @isTest
    static void test()
    {
        Patch__c patch = new Patch__c(Patch_Name__c='acme', Active__c=true, RSM__c=UserInfo.getUserId(), ProcessingSequence__c=1);
        insert patch;
        
        PageReference ref = new PageReference('/apex/PatchUserReplace?uid=' + UserInfo.getUserId() + '&pid=' + patch.Id);
        Test.setCurrentPage(ref);
        PatchUserReplaceController controller = new PatchUserReplaceController();
        List<SelectOption> patches = controller.Patches;
        System.assertEquals(2, patches.size());
        controller.save();
    }
    @isTest
    static void testSalesTeam()
    {
        Patch__c patch = new Patch__c(Patch_Name__c='acme', IsSalesTeam__c=true, Active__c=true, RSM__c=UserInfo.getUserId(), ProcessingSequence__c=1);
        insert patch;
        SalesTeam__c salesTeam = new SalesTeam__c(Patch__c=patch.Id, type__c='Enterprise');
        insert salesTeam;
        SalesTeamMember__c member = new SalesTeamMember__c(User__c =UserInfo.getUserId(), Role__c='SE', SalesTeam__c=salesTeam.Id);
        insert member;
        
        PageReference ref = new PageReference('/apex/PatchUserReplace?uid=' + UserInfo.getUserId() + '&pid=' + patch.Id);
        Test.setCurrentPage(ref);
        PatchUserReplaceController controller = new PatchUserReplaceController();
        List<SelectOption> patches = controller.Patches;
        System.assertEquals(2, patches.size());
        controller.save();
    }
}