objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quote_Date__c</fullName>
        <description>Quote Date</description>
        <label>Quote Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Quote_Valid_Until__c</fullName>
        <description>Quote Valid Until</description>
        <label>Quote Valid Until</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Tier_1_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Tier 1 Partner</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.IsAPartner__c</field>
                <operation>equals</operation>
                <value>1</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Silver Peak Quotes</relationshipLabel>
        <relationshipName>Tier1Partners</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Quote_Line__c.object
<CustomObject>
    <fields>
        <fullName>ApprovalLevel__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This field decide the Quote Line&apos; s approval level. It gets value from &apos;initApprovalLevel&apos; trigger. The custom setting &apos;Quote Approval Matrix&apos; finally defines the level of the Quote Line through its Type and Discount.
Type: 
a) Physical (Physical Appliance)
b) VIrtual (Virtual Appliance )
c) New Business( Subscription Product for Virtual Appliance on Opp type of New Business )

Line Item approval level requirements are: 
for &quot;a&quot;, over 35% goes to level 1, over 45% goes to level 2 and over 50% goes to level 3 
for &quot;b&quot;, over 45% goes to level 1, over 50% goes to level 2 and over 60% goes to level 3 
for &quot;c&apos;, over 50% goes to level 1, over 60% goes to level 2 and over 70% goes to level 3</description>
        <label>Approval Level</label>
        <precision>1</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Percent__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Discount Percent</label>
        <precision>6</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Product__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Quantity</label>
        <precision>11</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>Quote_Lines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Unit Price</label>
        <precision>14</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{00000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestSetApprovalLevelOnQuoteLine.cls
@IsTest
public class TestSetApprovalLevelOnQuoteLine {
    @IsTest(SeeAllData=true)
    public static void CheckApprovalLevel_EdgeConnect()
    {
        PriceBook2 pb1 = [select Id from Pricebook2 where Name='Enterprise' limit 1];
        User testUser = [select Id from User where IsActive=true and Id != :UserInfo.getUserId() limit 1];
        Account account = new Account(Name='acme', ownerId = testUser.Id,Registered_Discount_Product__c=10,Registered_Discount_EdgeConnect__c=20,Registered_Discount_Service__c=30);
        insert account;
        Account tierAcc = new Account(Name='acme',Type='Partner',Partner_Type__c='Reseller',Reseller_Agreement__c=true, ownerId = testUser.Id,Registered_Discount_Product__c=10,Registered_Discount_EdgeConnect__c=20,Registered_Discount_Service__c=30);
        insert tierAcc;
        Product2 product = new Product2(Name='EC-BASE-1Y',Product_Type__c='EDGECONNECT', Product_Category__c='Subscription', Family = 'Virtual Image');
        insert product;
        Opportunity opp = new Opportunity(OwnerId = testUser.Id, Technical_Responsible__c = testUser.Id, Name='acme', AccountId=account.Id, StageName='Discovery', CloseDate=System.today());
        insert opp;
        PricebookEntry entry = [select Id, Product2Id, UnitPrice from PricebookEntry where PriceBook2Id=:pb1.Id and isActive = true limit 1];
        OpportunityLineItem oppLineItem = new OpportunityLineItem(OpportunityId = opp.Id, PricebookEntryId = entry.Id, Quantity = 123, TotalPrice = 1300);//, Product2Id = product.Id);
        insert oppLineItem;
        Quote__c quote = new Quote__c(Opportunity__c = opp.Id, Tier_1_Partner__c=tierAcc.id, Quote_Date__c = date.Today(), Quote_Valid_Until__c = date.Today()+10);
        insert quote;
        Quote_Line__c quoteLine = new Quote_Line__c(Quote__c = quote.Id, Product__c = product.Id, Unit_Price__c = 234, Quantity__c = 123, Discount_Percent__c = 25);
        insert quoteLine;
        Quote_Line__c quoteLinetest = [select ApprovalLevel__c, Id from Quote_Line__c where Id =: quoteLine.Id];
        system.assertEquals(quoteLinetest.ApprovalLevel__c, 1);
    }
    @IsTest(SeeAllData=true)
    public static void CheckApprovalLevel_NXVX()
    {
        PriceBook2 pb1 = [select Id from Pricebook2 where Name='Enterprise' limit 1];
        User testUser = [select Id from User where IsActive=true and Id != :UserInfo.getUserId() limit 1];
        Account account = new Account(Name='acme', ownerId = testUser.Id,Registered_Discount_Product__c=10,Registered_Discount_EdgeConnect__c=20,Registered_Discount_Service__c=30);
        insert account;
        Account tierAcc = new Account(Name='acme',Type='Partner',Partner_Type__c='Reseller',Reseller_Agreement__c=true, ownerId = testUser.Id,Registered_Discount_Product__c=10,Registered_Discount_EdgeConnect__c=20,Registered_Discount_Service__c=30);
        insert tierAcc;
        Product2 product = new Product2(Name='VX-2000',Model__c='VX-2000',Product_Type__c='NX/VX', Product_Category__c='Subscription', Family = 'Virtual Image');
        insert product;
        Opportunity opp = new Opportunity(OwnerId = testUser.Id, Technical_Responsible__c = testUser.Id, Name='acme', Primary_Partner__c=account.Id, AccountId=account.Id, StageName='Discovery', CloseDate=System.today());
        insert opp;
        PricebookEntry entry = [select Id, Product2Id, UnitPrice from PricebookEntry where  PriceBook2Id=:pb1.Id and isActive = true limit 1];
        OpportunityLineItem oppLineItem = new OpportunityLineItem(OpportunityId = opp.Id, PricebookEntryId = entry.Id, Quantity = 123, TotalPrice = 1300);//, Product2Id = product.Id);
        insert oppLineItem;
        Quote__c quote = new Quote__c(Opportunity__c = opp.Id, Tier_1_Partner__c=tierAcc.id,Quote_Date__c = date.Today(), Quote_Valid_Until__c = date.Today()+10);
        insert quote;
        Quote_Line__c quoteLine = new Quote_Line__c(Quote__c = quote.Id, Product__c = product.Id, Unit_Price__c = 234, Quantity__c = 123, Discount_Percent__c = 15);
        insert quoteLine;
        Quote_Line__c quoteLinetest = [select ApprovalLevel__c, Id from Quote_Line__c where Id =: quoteLine.Id];
        system.assertEquals(quoteLinetest.ApprovalLevel__c, 1);
    }
    @IsTest(SeeAllData=true)
    public static void CheckApprovalLevel_Main()
    {
        PriceBook2 pb1 = [select Id from Pricebook2 where Name='Enterprise' limit 1];
        User testUser = [select Id from User where IsActive=true and Id != :UserInfo.getUserId() limit 1];
        Account account = new Account(Name='acme', ownerId = testUser.Id,Registered_Discount_Product__c=10,Registered_Discount_EdgeConnect__c=20,Registered_Discount_Service__c=30);
        insert account;
        Product2 product = new Product2(Name='NX-7700-RENEWAL-CONTRACT',Model__c='NX-7700',Product_Type__c='NX/VX', Product_Category__c='Maintenance-1 Day', Family = 'Service');
        insert product;
        Opportunity opp = new Opportunity(OwnerId = testUser.Id, Technical_Responsible__c = testUser.Id, Name='acme', Primary_Partner__c=account.Id, AccountId=account.Id, StageName='Discovery', CloseDate=System.today());
        insert opp;
        PricebookEntry entry = [select Id, Product2Id, UnitPrice from PricebookEntry where  PriceBook2Id=:pb1.Id and isActive = true limit 1];
        OpportunityLineItem oppLineItem = new OpportunityLineItem(OpportunityId = opp.Id, PricebookEntryId = entry.Id, Quantity = 123, TotalPrice = 1300);//, Product2Id = product.Id);
        insert oppLineItem;
        Quote__c quote = new Quote__c(Opportunity__c = opp.Id, Quote_Date__c = date.Today(), Quote_Valid_Until__c = date.Today()+10);
        insert quote;
        Quote_Line__c quoteLine = new Quote_Line__c(Quote__c = quote.Id, Product__c = product.Id, Unit_Price__c = 234, Quantity__c = 123, Discount_Percent__c = 40);
        insert quoteLine;
        Quote_Line__c quoteLinetest = [select ApprovalLevel__c, Id from Quote_Line__c where Id =: quoteLine.Id];
        system.assertEquals(quoteLinetest.ApprovalLevel__c, 3);
    }

}