objects/Quote__c.object
<CustomObject>
    <description>Quote</description>
    <fields>
        <fullName>Approval_Level_Needed__c</fullName>
        <description>Equals to the max approval level of the quote lines</description>
        <formula>MAX(
if( Quote_Discount__c &lt;0,3,0),
IF(and(ispickval( Opportunity__r.Type ,&apos;Training/WanStart&apos;), ( Opportunity__r.Account.IsAPartner__c &lt;&gt;1 )),3,0),
ApprovalLevelMax__c
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>if( Level3Required__c =1,3,

MAX(ApprovalLevelMax__c,
Approval_Required__c,
if(Opportunity__r.Primary_Partner__r.CreditHold__c,2,0) ,
if( Service_Discount_Max__c &gt; RegPartServDisc__c ,3,0)
))</inlineHelpText>
        <label>Approval Level Needed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Approval_Made__c</fullName>
        <defaultValue>false</defaultValue>
        <description>check this box in the approval stage and then only uncheck it if the discount percentage changes again</description>
        <label>Approval Made</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Approval_Required__c</fullName>
        <description>Formula for Quote Approval Matrix - 06-12-10: IF(or( 
AND( 
OR( 
and(Discount_Max__c &gt; 0.35, Discount_Max__c &gt; RegPartProdDisc__c ), 
Average_Discount__c &gt; 0.0, 
and( Service_Discount_Max__c &gt; 0.15, Service_Discount_Max__c &gt; RegPartServDisc__c )), 
Approval_Made__c =FALSE), OR(and(ConsultingDiscountMax__c &gt;0,Opportunity__r.Account.IsAPartner__c =0) ,AND(ConsultingDiscountMax__c &gt;0.50, Opportunity__r.Account.IsAPartner__c =1))), 
1, 0)
Updated for tiering 6-24-2010
IF(or( 
AND( 
OR( 
and(Discount_Max__c &gt; 0.35, Discount_Max__c &gt; RegPartProdDisc__c ), 
Average_Discount__c &gt; 0.0, 
and( OR( and(Service_Discount_Max__c &gt; 0.21, MultiYearValue__c =2), and(Service_Discount_Max__c &gt; 0.27, MultiYearValue__c =3), Service_Discount_Max__c &gt; 0.15), Service_Discount_Max__c &gt; RegPartServDisc__c )), 
Approval_Made__c =FALSE), OR(and(ConsultingDiscountMax__c &gt;0,Opportunity__r.Account.IsAPartner__c =0) ,AND(ConsultingDiscountMax__c &gt;0.50, Opportunity__r.Account.IsAPartner__c =1))), 
1, 0)</description>
        <formula>If(
OR(Approval_Level_Needed__c &gt;0, Level3Required__c==1)
,1,0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Approval Required</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Discount_Justification__c</fullName>
        <inlineHelpText>Note to send to approvers to communicate reason for requesting the discount</inlineHelpText>
        <label>Discount Justification</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Primary</description>
        <label>Primary</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Reseller_AccountId__c</fullName>
        <formula>IF(NOT(ISBLANK(Tier_3_Partner__c)),Tier_3_Partner__c,
IF(NOT(ISBLANK(Tier_2_Partner__c)),Tier_2_Partner__c,
Tier_1_Partner__c
)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Reseller AccountId</label>
        <type>Text</type>
    </fields>
    <label>Silver Peak Quote</label>
    <nameField>
        <displayFormat>Q{00000000}</displayFormat>
        <label>Quote ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Silver Peak Quotes</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/QuoteExtension.cls
/**
 *  The extension class for Quote page, overriding Submit for Approval button.
 */

public class QuoteExtension
{
    static final String MESSAGE_SUCCEEDED = 'Succeeded';
    
    public QuoteExtension(ApexPages.StandardController ctrl)
    {
    
    }
    
    @RemoteAction
    public static Boolean CheckQuote(String quoteId, String opportunityId)
    {
        Integer quoteCount = [select count() from Quote__c where Opportunity__c = :opportunityId and Id != :quoteId];
        return quoteCount > 0;
    }
    
    @RemoteAction
    public static String SetPrimaryQuoteAndSubmit(String quoteId, String opportunityId)
    {
        Opportunity resultOpp=null;
        List<Quote__c> quotes = [select Id, Primary__c,Reseller_AccountId__c from Quote__c where Opportunity__c = :opportunityId];
        if(!quotes.isEmpty())
        {
            for(Quote__c quote : quotes)
            {
                quote.Primary__c = (quote.Id == quoteId) ? true : false;
                if(quote.Primary__c)
                     resultOpp= new Opportunity(Id=opportunityId, Primary_Partner__c=quote.Reseller_AccountId__c);
            }
            try
            {
                update quotes;
                update resultOpp;
            }
            catch(Exception ex)
            {
                return ex.getMessage();
            }
        }
        return SubmitForApproval(quoteId);
    }
    
    @RemoteAction
    public static String SubmitForApproval(String quoteId)
    {
        try
        {
            // Validate the entry criteria and then send for approval
            if(quoteId!=null)
            {
                List<Quote__c> lstQuote =[Select Id,Approval_Required__c,Approval_Made__c,Approval_Level_Needed__c,Discount_Justification__c,Opportunity__r.Geo_Region__c from Quote__c where Id=:quoteId];
                if(lstQuote!=null && lstQuote.size()>0)
                {
                    Quote__c quoteObj= lstQuote[0];
                    if(Userinfo.getLastName()!='Beckus')
                    {
                        string errorMsg=ValidateApprovalEntryCriterias(quoteObj);
                        if(errorMsg!='')
                        {
                            return errorMsg;
                        }
                    }
                    Approval.ProcessSubmitRequest request = new Approval.ProcessSubmitRequest();
                    request.setObjectId(quoteId);
                    Approval.ProcessResult result = Approval.process(request);
                    if(result.isSuccess())
                    {
                        return MESSAGE_SUCCEEDED;
                    }
                    else
                    {
                        return result.getErrors()[0].getMessage();
                    }
                }
            }
        }
        catch(Exception ex)
        {
            return ex.getMessage();
        }
        
        return '';
    }
    
    private static string ValidateApprovalEntryCriterias(Quote__c quoteObj)
    {
        System.debug(quoteObj.Opportunity__r.Geo_Region__c);
        if(quoteObj.Approval_Required__c==0)
            return 'Approval process is not required. Its already approved.';
        if(quoteObj.Approval_Required__c==1 && quoteObj.Opportunity__r.Geo_Region__c =='NONE')
            return 'GEO is blank on the opportunity.Please populate this value or contact sales operations.';        
        if(quoteObj.Approval_Required__c==1 && string.isBlank(quoteObj.Discount_Justification__c))
            return 'Discount Justification is empty. Please provide comments.';
        return'';  
    }
}