objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Contract_Number__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contract Number</label>
        <referenceTo>Contract</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>POC_Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped- Pending Extension Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <inlineHelpText>This is the date the POC request is approved to run to</inlineHelpText>
        <label>POC Expiration Date</label>
        <type>Date</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/DeleteSPContractsForExpiredPOCScheduler.cls
public class DeleteSPContractsForExpiredPOCScheduler implements Schedulable{
    public void execute(SchedulableContext sc)
    {
        List<Contract> lstContractsToDelete= new List<Contract>();
        List<Request__c> lstData = [select Id,Contract_Number__c,(Select Id from Assets__r where Product2.Family='Virtual Image' and Status='Customer Evaluation') from Request__c where Opportunity__r.Account.ECSP__c=true and Target_End_Date__c=:Date.today() and Status__c in('Pending Return','Pending Return - Invoiced','Closed - Returned','Closed - Won') and Contract_Number__c!=null and Contract_Number__r.Contract_Type__c='Evaluation'];
        if(lstData!=null && lstData.size()>0)
        {
            for(Request__c item:lstData)
            {
                List<Asset> lstAssets=item.Assets__r;
                if(lstAssets.size()==0)
                {
                    lstContractsToDelete.add(new Contract(Id=item.Contract_Number__c));
                }
                if(lstContractsToDelete!=null && lstContractsToDelete.size()>0)
                {
                    delete lstContractsToDelete;
                }
                
            }
        }
        
        
    }
}