objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>IsAllVirtual__c</fullName>
        <formula>IF( 

OR( 
LEFT(TEXT( Evaluation_Product_1__c ) ,1) = &apos;N&apos;,
LEFT(TEXT( Evaluation_Product_2__c ) ,1) = &apos;N&apos;, 
CONTAINS(TEXT( Evaluation_Product_1__c ) ,&apos;GX-1000&apos;), 
CONTAINS(TEXT( Evaluation_Product_2__c ) ,&apos;GX-1000&apos;),
NOT(ISBLANK(TEXT( PhysicalProduct1__c )))

), 0,1)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>IsAllVirtual</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Term +Orch-SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Metered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Metered +Orch-SP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Approved to Ship</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped - Extended</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Return - Invoiced</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Denied</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed - Returned</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Approvals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped- Pending Extension Approval</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Target_End_Date__c</fullName>
        <inlineHelpText>This is the date the POC request is approved to run to</inlineHelpText>
        <label>POC Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>VirtualProduct1__c</fullName>
        <label>Virtual Product1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unity Cloud Intelligence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VirtualProduct5__c</fullName>
        <label>Virtual Product5</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity1__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Virtual Quantity1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity5__c</fullName>
        <label>Virtual Quantity5</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestAutomatePOCRenewalExtensions.cls
@IsTest
public class TestAutomatePOCRenewalExtensions {
    
    @IsTest(SeeAllData=True)
    public static void TestPocRenewalAssets_EdgeConnect()
    {
        
        Account acc = new Account(Name='testECPOC');
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Account spacc = new Account(Name='Silver Peak Systems');
        insert spacc;
        Profile prof = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User techUser = new User(Alias = 'standt', Email='testUser@testtechuser.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = prof.Id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='testUser@testtechuser.com');
        
        techUser.IsActive =true;
        insert techUser;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Discovery';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Product_Type__c='Both';
        opportunity.Technical_Responsible__c=UserInfo.getUserId();
        opportunity.OwnerId=UserInfo.getUserId();
        insert opportunity;
        
        Request__c request = new Request__c(POC_Contact__c = contact.Id);
        request.POC_Type__c='EdgeConnect';
        request.Opportunity__c= opportunity.id;
        request.VirtualProduct5__c= 'EC-ORCH';
        request.VirtualQuantity5__c= 1;
        insert request;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(request);
        CustomPOCRequestController controller = new CustomPOCRequestController(stdController);
        controller.savePage();
        
        
        System.runAs(techUser)
        {
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(request);
            VirtualPOCFulfillmentController vircontroller = new VirtualPOCFulfillmentController(sc);
            vircontroller.save();
            List<Asset> asset = [Select License_End_Date__c,Product2.Name from Asset where POCRequest__c =: request.Id];
            System.assert(asset.size()>0);
            
            Request__C output=[Select Id,IsAllVirtual__c,Status__c,Target_End_Date__c from Request__c where Id=:request.Id];
            System.debug('output.IsAllVirtual__c'+output.IsAllVirtual__c);
            request.Status__c='Shipped - Extended';
            request.Target_End_Date__c=Date.today().addDays(10);
            update request;
            List<Asset> asset1 = [Select License_End_Date__c,Product2.Name,Is_Asset_Eligible_For_POC_Renewal_Ext__c from Asset where POCRequest__c =: request.Id];
            System.debug('output.Is_Asset_Eligible_For_POC_Renewal_Ext__c'+asset1[0].Is_Asset_Eligible_For_POC_Renewal_Ext__c);
            AutomatePOCRenewalExtensions obj = new AutomatePOCRenewalExtensions();
            Database.executeBatch(obj,1);
            Test.stopTest();
        }
        
      
        
        
    }
    
    @IsTest(SeeAllData=True)
    public static void TestPocRenewalAssets_ServiceProvider()
    {
        
        Account acc = new Account(Name='testECPOC',Partner_Type__c='Service Provider',ECSP__c=true);
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Account spacc = new Account(Name='Silver Peak Systems');
        insert spacc;
        Profile prof = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User techUser = new User(Alias = 'standt', Email='testUser@testtechuser.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = prof.Id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='testUser@testtechuser.com');
        
        techUser.IsActive =true;
        insert techUser;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Discovery';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Product_Type__c='Both';
        opportunity.Technical_Responsible__c=UserInfo.getUserId();
        opportunity.OwnerId=UserInfo.getUserId();
        insert opportunity;
        
        Request__c request = new Request__c(POC_Contact__c = contact.Id);
        request.POC_Type__c='Service Provider';
        request.Opportunity__c= opportunity.id;
        insert request;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(request);
        CustomPOCRequestController controller = new CustomPOCRequestController(stdController);
        controller.savePage();
        
        
        System.runAs(techUser)
        {
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(request);
            VirtualPOCFulfillmentController vircontroller = new VirtualPOCFulfillmentController(sc);
            vircontroller.save();
            List<Asset> asset = [Select License_End_Date__c,Product2.Name from Asset where POCRequest__c =: request.Id];
            System.assert(asset.size()>0);
            
            Request__C output=[Select Id,IsAllVirtual__c,Status__c,Target_End_Date__c from Request__c where Id=:request.Id];
            System.debug('output.IsAllVirtual__c'+output.IsAllVirtual__c);
            request.Status__c='Shipped - Extended';
            request.Target_End_Date__c=Date.today().addDays(10);
            update request;
            List<Asset> asset1 = [Select License_End_Date__c,Product2.Name,Is_Asset_Eligible_For_POC_Renewal_Ext__c from Asset where POCRequest__c =: request.Id];
            System.debug('output.Is_Asset_Eligible_For_POC_Renewal_Ext__c'+asset1[0].Is_Asset_Eligible_For_POC_Renewal_Ext__c);
            AutomatePOCRenewalExtensions obj = new AutomatePOCRenewalExtensions();
            Database.executeBatch(obj,1);
            Test.stopTest();
        }
        
       
        
        
    }
    
    @IsTest(SeeAllData=True)
    public static void TestPocRenewalAssets_WanOp()
    {
        
        Account acc = new Account(Name='testECPOC');
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Account spacc = new Account(Name='Silver Peak Systems');
        insert spacc;
        Profile prof = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User techUser = new User(Alias = 'standt', Email='testUser@testtechuser.com', 
                                 EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                 LocaleSidKey='en_US', ProfileId = prof.Id, 
                                 TimeZoneSidKey='America/Los_Angeles', UserName='testUser@testtechuser.com');
        
        techUser.IsActive =true;
        insert techUser;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Discovery';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Product_Type__c='Both';
        opportunity.Technical_Responsible__c=UserInfo.getUserId();
        opportunity.OwnerId=UserInfo.getUserId();
        insert opportunity;
        
        Request__c request = new Request__c(POC_Contact__c = contact.Id);
        request.POC_Type__c='WAN Op';
        request.Opportunity__c= opportunity.id;
        request.VirtualProduct1__c='VX 500';
        request.VirtualQuantity1__c=1;
        insert request;
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(request);
        CustomPOCRequestController controller = new CustomPOCRequestController(stdController);
        controller.savePage();
        
        
        System.runAs(techUser)
        {
            Test.startTest();
            ApexPages.StandardController sc = new ApexPages.StandardController(request);
            VirtualPOCFulfillmentController vircontroller = new VirtualPOCFulfillmentController(sc);
            vircontroller.save();
            List<Asset> asset = [Select License_End_Date__c,Product2.Name from Asset where POCRequest__c =: request.Id];
            System.assert(asset.size()>0);
            
            Request__C output=[Select Id,IsAllVirtual__c,Status__c,Target_End_Date__c from Request__c where Id=:request.Id];
            System.debug('output.IsAllVirtual__c'+output.IsAllVirtual__c);
            request.Status__c='Shipped - Extended';
            request.Target_End_Date__c=Date.today().addDays(10);
            update request;
            List<Asset> asset1 = [Select License_End_Date__c,Product2.Name,Is_Asset_Eligible_For_POC_Renewal_Ext__c from Asset where POCRequest__c =: request.Id];
            System.debug('output.Is_Asset_Eligible_For_POC_Renewal_Ext__c'+asset1[0].Is_Asset_Eligible_For_POC_Renewal_Ext__c);
            AutomatePOCRenewalExtensions obj = new AutomatePOCRenewalExtensions();
            Database.executeBatch(obj,1);
            Test.stopTest();
        }
    }    
    
    
}