objects/Request__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>POC Requests</relationshipLabel>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>link to contact record for POC communications</inlineHelpText>
        <label>POC Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Requests</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>POC_Type__c</fullName>
        <label>POC Type</label>
        <picklist>
            <picklistValues>
                <fullName>WAN Op</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EdgeConnect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Term</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Term +Orch-SP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Metered</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EC-SP-Metered +Orch-SP</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RSM_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM Sales Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_RSMM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM_VP_Sales__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM VP Sales</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_VP</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RSM__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>RSM</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_RSM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SE_Director__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE Director</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_SED</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SE_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE Manager</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_SEM</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SE__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>SE</label>
        <referenceTo>User</referenceTo>
        <relationshipName>POC_Requests_SE</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Service_Provider_Account_Type__c</fullName>
        <formula>TEXT(Opportunity__r.Account.Service_Provider_Account_Type__c )</formula>
        <label>Service Provider Account Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_POC_Approvers__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Trigger POC Approvers</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>VirtualProduct1__c</fullName>
        <label>Virtual Product1</label>
        <picklist>
            <picklistValues>
                <fullName>VX 500</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 1000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 2000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 3000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 5000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 6000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 7000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 8000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VX 9000</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-6</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VRX-8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GMS-10</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unity Cloud Intelligence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>VirtualQuantity1__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Virtual Quantity1</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>POC Request</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>POC Requests</pluralLabel>
    <recordTypes>
        <fullName>New</fullName>
        <active>true</active>
        <label>New</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

classes/TestPopulatePOCApprovers.cls
@IsTest
public class TestPopulatePOCApprovers {
   /* @IsTest
    public static void TestApprovers_SP()
    {
        Account acc = new Account(Name='testECPOC',ECSP__c=true,Service_Provider_Account_Type__c='Perpetual',Service_Provider_Admin_User__c='abc@abc.com',Service_Provider_Domain__c='abc1323',Service_Provider_Location__c='Canada (Central)');
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Account spAcc = new Account(Name='Silver Peak Systems');
        insert spAcc;
        Account speAcc = new Account(Name='EMAIL SUPPORT CONTACTS');
        insert speAcc;
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User owner2ndManagerId = new User(Alias = 'standt', Email='testUser2@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, 
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser2@uniquetest.com',IsActive=true);
        
        insert owner2ndManagerId;
        User owner1stManagerId = new User(Alias = 'standt', Email='testUser1@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner2ndManagerId.Id,
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser1@uniquetest.com',IsActive=true);
        
        insert owner1stManagerId;
        User ownerId = new User(Alias = 'standt', Email='testUser@uniquetest.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner1stManagerId.Id,
                                TimeZoneSidKey='America/Los_Angeles', UserName='testUser@uniquetest.com',IsActive=true);
        
        insert ownerId;
        
        User SE2ndManagerId = new User(Alias = 'standt', Email='testUser3@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, 
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser3@uniquetest.com',IsActive=true);
        
        insert SE2ndManagerId;
        User SE1stManagerId = new User(Alias = 'standt', Email='testUser4@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE2ndManagerId.Id,
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser4@uniquetest.com',IsActive=true);
        
        insert SE1stManagerId;
        User SEId = new User(Alias = 'standt', Email='testUser5@uniquetest.com', 
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE1stManagerId.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='testUser5@uniquetest.com',IsActive=true);
        
        insert SEId;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Closed Dead';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Product_Type__c = 'Both';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Solution_Type__c = 'Replication Acceleration';
        opportunity.Technical_Responsible__c=SEId.Id;
        opportunity.OwnerId=ownerId.Id;
        insert opportunity;
        Request__c pocRequest = new Request__c(POC_Contact__c = contact.Id);
        pocRequest.POC_Type__c='Perpetual';
        pocRequest.Opportunity__c= opportunity.id;
        pocRequest.VirtualProduct1__c= 'EC-SP-50';
        pocRequest.VirtualQuantity1__c= 5;
        pocRequest.VirtualProduct1__c= 'EC-SP-100';
        pocRequest.VirtualQuantity1__c= 5;
        pocRequest.VirtualProduct1__c= 'EC-SP-200';
        pocRequest.VirtualQuantity1__c= 5;
        pocRequest.VirtualProduct1__c= 'EC-SP-1000';
        pocRequest.VirtualQuantity1__c= 5;
        insert pocRequest;  
        Request__c output=[Select Id , RSM__c,SE__c,RSM_Manager__c,RSM_VP_Sales__c,SE_Manager__c,SE_Director__c from Request__c where Id=:pocRequest.Id] ;
        System.assert(output.RSM_Manager__c!=null);
        System.assert(output.RSM__c!=null);
        System.assert(output.RSM_VP_Sales__c!=null);
        System.assert(output.SE_Manager__c!=null);
        System.assert(output.SE_Director__c!=null);
        System.assert(output.SE__c!=null);
    }
    */
    @IsTest
    public static void TestApprovers_NAM()
    {
        Account acc = new Account(Name='testECPOC');
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Account spAcc = new Account(Name='Silver Peak Systems');
        insert spAcc;
        Account speAcc = new Account(Name='EMAIL SUPPORT CONTACTS');
        insert speAcc;
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User owner2ndManagerId = new User(Alias = 'standt', Email='testUser2@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, 
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser2@uniquetest.com',IsActive=true);
        
        insert owner2ndManagerId;
        User owner1stManagerId = new User(Alias = 'standt', Email='testUser1@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner2ndManagerId.Id,
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser1@uniquetest.com',IsActive=true);
        
        insert owner1stManagerId;
        User ownerId = new User(Alias = 'standt', Email='testUser@uniquetest.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner1stManagerId.Id,
                                TimeZoneSidKey='America/Los_Angeles', UserName='testUser@uniquetest.com',IsActive=true);
        
        insert ownerId;
        
        User SE2ndManagerId = new User(Alias = 'standt', Email='testUser3@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, 
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser3@uniquetest.com',IsActive=true);
        
        insert SE2ndManagerId;
        User SE1stManagerId = new User(Alias = 'standt', Email='testUser4@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE2ndManagerId.Id,
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser4@uniquetest.com',IsActive=true);
        
        insert SE1stManagerId;
        User SEId = new User(Alias = 'standt', Email='testUser5@uniquetest.com', 
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE1stManagerId.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='testUser5@uniquetest.com',IsActive=true);
        
        insert SEId;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Closed Dead';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Product_Type__c = 'Both';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Solution_Type__c = 'Replication Acceleration';
        opportunity.Technical_Responsible__c=SEId.Id;
        opportunity.OwnerId=ownerId.Id;
        opportunity.Sales_Region__c='NAM-central';
        insert opportunity;
        Request__c pocRequest = new Request__c(POC_Contact__c = contact.Id);
        pocRequest.POC_Type__c='WAN Op';
        pocRequest.Opportunity__c= opportunity.id;
        pocRequest.VirtualProduct1__c= 'VX-2000';
        pocRequest.VirtualQuantity1__c= 5;
        
        insert pocRequest;  
        Request__c output=[Select Id , RSM__c,SE__c,RSM_Manager__c,RSM_VP_Sales__c,SE_Manager__c,SE_Director__c from Request__c where Id=:pocRequest.Id] ;
        System.assert(output.RSM_Manager__c!=null);
        System.assert(output.RSM__c!=null);
        System.assert(output.RSM_VP_Sales__c!=null);
        System.assert(output.SE_Manager__c!=null);
        System.assert(output.SE_Director__c!=null);
        System.assert(output.SE__c!=null);
    }
    @IsTest
    public static void TestApprovers_APAC()
    {
        Account acc = new Account(Name='testECPOC');
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Account spAcc = new Account(Name='Silver Peak Systems');
        insert spAcc;
        Account speAcc = new Account(Name='EMAIL SUPPORT CONTACTS');
        insert speAcc;
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User owner2ndManagerId = new User(Alias = 'standt', Email='testUser2@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, 
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser2@uniquetest.com',IsActive=true);
        
        insert owner2ndManagerId;
        User owner1stManagerId = new User(Alias = 'standt', Email='testUser1@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner2ndManagerId.Id,
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser1@uniquetest.com',IsActive=true);
        
        insert owner1stManagerId;
        User ownerId = new User(Alias = 'standt', Email='testUser@uniquetest.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner1stManagerId.Id,
                                TimeZoneSidKey='America/Los_Angeles', UserName='testUser@uniquetest.com',IsActive=true);
        
        insert ownerId;
        
        User SE2ndManagerId = new User(Alias = 'standt', Email='testUser3@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, 
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser3@uniquetest.com',IsActive=true);
        
        insert SE2ndManagerId;
        User SE1stManagerId = new User(Alias = 'standt', Email='testUser4@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE2ndManagerId.Id,
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser4@uniquetest.com',IsActive=true);
        
        insert SE1stManagerId;
        User SEId = new User(Alias = 'standt', Email='testUser5@uniquetest.com', 
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE1stManagerId.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='testUser5@uniquetest.com',IsActive=true);
        
        insert SEId;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Closed Dead';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Product_Type__c = 'Both';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Solution_Type__c = 'Replication Acceleration';
        opportunity.Technical_Responsible__c=SEId.Id;
        opportunity.OwnerId=ownerId.Id;
        opportunity.Sales_Region__c='APAC';
        insert opportunity;
        Request__c pocRequest = new Request__c(POC_Contact__c = contact.Id);
        pocRequest.POC_Type__c='WAN Op';
        pocRequest.Opportunity__c= opportunity.id;
        pocRequest.VirtualProduct1__c= 'VX-2000';
        pocRequest.VirtualQuantity1__c= 5;
        
        insert pocRequest;  
        Request__c output=[Select Id , RSM__c,SE__c,RSM_Manager__c,RSM_VP_Sales__c,SE_Manager__c,SE_Director__c from Request__c where Id=:pocRequest.Id] ;
        System.assert(output.RSM_Manager__c!=null);
        System.assert(output.RSM__c!=null);
        System.assert(output.RSM_VP_Sales__c!=null);
        System.assert(output.SE_Manager__c!=null);
        System.assert(output.SE_Director__c!=null);
        System.assert(output.SE__c!=null); 
    }
    @IsTest
    public static void TestApprovers_Update()
    {
        Account acc = new Account(Name='testECPOC');
        insert acc;
        Contact contact = new Contact(FirstName = 'AcmeFirstname', LastName = 'AcmeLastname', Phone='123456789', Email = 'acme@acme.com' , accountId=acc.Id);
        insert contact;
        Account spAcc = new Account(Name='Silver Peak Systems');
        insert spAcc;
        Account speAcc = new Account(Name='EMAIL SUPPORT CONTACTS');
        insert speAcc;
        Profile p = [SELECT Id FROM Profile WHERE Name='System Administrator']; 
        User owner2ndManagerId = new User(Alias = 'standt', Email='testUser2@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, 
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser2@uniquetest.com',IsActive=true);
        
        insert owner2ndManagerId;
        User owner1stManagerId = new User(Alias = 'standt', Email='testUser1@uniquetest.com', 
                                          EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                          LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner2ndManagerId.Id,
                                          TimeZoneSidKey='America/Los_Angeles', UserName='testUser1@uniquetest.com',IsActive=true);
        
        insert owner1stManagerId;
        User ownerId = new User(Alias = 'standt', Email='testUser@uniquetest.com', 
                                EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                LocaleSidKey='en_US', ProfileId = p.Id, managerId=owner1stManagerId.Id,
                                TimeZoneSidKey='America/Los_Angeles', UserName='testUser@uniquetest.com',IsActive=true);
        
        insert ownerId;
        
        User SE2ndManagerId = new User(Alias = 'standt', Email='testUser3@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, 
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser3@uniquetest.com',IsActive=true);
        
        insert SE2ndManagerId;
        User SE1stManagerId = new User(Alias = 'standt', Email='testUser4@uniquetest.com', 
                                       EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                                       LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE2ndManagerId.Id,
                                       TimeZoneSidKey='America/Los_Angeles', UserName='testUser4@uniquetest.com',IsActive=true);
        
        insert SE1stManagerId;
        User SEId = new User(Alias = 'standt', Email='testUser5@uniquetest.com', 
                             EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
                             LocaleSidKey='en_US', ProfileId = p.Id, managerId=SE1stManagerId.Id,
                             TimeZoneSidKey='America/Los_Angeles', UserName='testUser5@uniquetest.com',IsActive=true);
        
        insert SEId;
        Opportunity opportunity = new Opportunity();
        opportunity.Name = 'acme';
        opportunity.AccountId = acc.Id;
        opportunity.Pricebook2Id = TestUtilities.getStandardPricebookId();
        opportunity.StageName = 'Closed Dead';
        opportunity.Dead_Reason__c = 'acme';
        opportunity.CloseDate = Date.today().addYears(1);
        opportunity.Type = 'New Business';
        opportunity.Opportunity_Source__c = 'Other';
        opportunity.POC_Type__c = 'POC';
        opportunity.Product_Type__c = 'Both';
        opportunity.Deal_Type__c = 'Replication';
        opportunity.Solution_Type__c = 'Replication Acceleration';
        opportunity.Technical_Responsible__c=SEId.Id;
        opportunity.OwnerId=ownerId.Id;
        opportunity.Sales_Region__c='APAC';
        insert opportunity;
        Request__c pocRequest = new Request__c(POC_Contact__c = contact.Id);
        pocRequest.POC_Type__c='WAN Op';
        pocRequest.Opportunity__c= opportunity.id;
        pocRequest.VirtualProduct1__c= 'VX-2000';
        pocRequest.VirtualQuantity1__c= 5;
        
        insert pocRequest;  
        Request__c output=[Select Id , RSM__c,SE__c,RSM_Manager__c,RSM_VP_Sales__c,SE_Manager__c,SE_Director__c from Request__c where Id=:pocRequest.Id] ;
        System.assert(output.RSM_Manager__c!=null);
        System.assert(output.RSM__c!=null);
        System.assert(output.RSM_VP_Sales__c!=null);
        System.assert(output.SE_Manager__c!=null);
        System.assert(output.SE_Director__c!=null);
        System.assert(output.SE__c!=null); 
        pocRequest.SE__c=null;
        pocRequest.SE_Director__c=null;
        pocRequest.SE_Manager__c=null;
        pocRequest.RSM__c=null;
        pocRequest.RSM_Manager__c=null;
        pocRequest.RSM_VP_Sales__c=null;
        update pocRequest;
        pocRequest.Trigger_POC_Approvers__c=true;
        update pocRequest;
        output=[Select Id , RSM__c,SE__c,RSM_Manager__c,RSM_VP_Sales__c,SE_Manager__c,SE_Director__c from Request__c where Id=:pocRequest.Id] ;
        System.assert(output.RSM_Manager__c!=null);
        System.assert(output.RSM__c!=null);
        System.assert(output.RSM_VP_Sales__c!=null);
        System.assert(output.SE_Manager__c!=null);
        System.assert(output.SE_Director__c!=null);
        System.assert(output.SE__c!=null);
        
    }
}