objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t29BEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email -Loc 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone -Loc 1</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Note_Loc_1__c</fullName>
        <label>Note -Loc 1</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return for Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <recordTypes>
        <fullName>RMA</fullName>
        <active>true</active>
        <description>Advance Replace, Repair and REcall RMAs</description>
        <label>RMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>AltProdPreviouslyOrdered__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>this is used to track that product that previously sent on an RMA</inlineHelpText>
        <label>Alternate Product Previously Ordered</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>RMA Items (Alternate Product Previously Ordered)</relationshipLabel>
        <relationshipName>AltRMAProd</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Email__c</fullName>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Contact_Phone__c</fullName>
        <label>Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2CyEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ship_To_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Ship To Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N500000021gyXEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Ship_to_address__c</fullName>
        <label>Ship-To Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return - Repair and Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return - Refurbish and Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance - Ship Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestRMAItemTriggerHandler.cls
@IsTest
public class TestRMAItemTriggerHandler {
  @isTest
    static void testChangeRMAItemProductAndUpdateRMAStatus()
    {
        List<Product2> prods = new List<Product2> { 
            new Product2(Name='acme1', ProductCode='pcode1'),
                new Product2(Name='acme2') };
                    insert prods;
        Product2 prod = new Product2(Name='acme', ProductCode='pcode', RMA_Alternate_1__c=prods[0].Id, RMA_Alternate_2__c=prods[1].Id,Product_Category__c='Appliance');
        insert prod;
        Account acc = new Account(Name='acme', Type='Eval');
        insert acc;
        Account spAccount= new Account(Name='Silver Peak Systems');
        insert spAccount;
        Contact con = new Contact(LastName='acme', AccountId=acc.Id);
        insert con;
        Asset asset = new Asset(Name='acme', SerialNumber='acme', Quantity=1.00, Status='Conditional PO', Product2Id=prod.Id, AccountId=acc.Id, ContactId=con.Id);
        insert asset;
        RMA__c rma = new RMA__c(Status__c='Initiated', Account__c=acc.Id);
        insert rma;
        RMA_Item__c item = new RMA_Item__c(RMA__c=rma.Id, Product2__c=prod.Id, Asset__c=asset.Id, Ship_To_Contact__c=con.Id, Ship_to_address__c='acme', Contact_Phone__c='12345678', Contact_Email__c='acme@acme.com');
        insert item;
        rma.Note_Loc_1__c = 'Part Number Not Active';
        rma.Status__c = 'Dispatch Rejected';
        update rma;
        rma.Note_Loc_1__c = 'Part Number Not Active';
        rma.Status__c = 'Dispatch Rejected';
        update rma;
    }
    
    @isTest
    static void testChangeRMAItemProduct()
    {
        Account spAccount= new Account(Name='Silver Peak Systems');
        insert spAccount;
        Product2 productA = new Product2(Name='A', ProductCode='A', IsActive=true,Product_Category__c='Appliance');
        Product2 productB = new Product2(Name='B', ProductCode='B', IsActive=true,Product_Category__c='Appliance');
        Product2 productC = new Product2(Name='C', ProductCode='C', IsActive=true,Product_Category__c='Appliance');
        Product2 productD = new Product2(Name='D', ProductCode='D', IsActive=true,Product_Category__c='Appliance');
        Product2 productE = new Product2(Name='E', ProductCode='E', IsActive=true,Product_Category__c='Appliance');
        Product2 productF = new Product2(Name='F', ProductCode='F', IsActive=true,Product_Category__c='Appliance');
        Product2 productG = new Product2(Name='G', ProductCode='G', IsActive=true,Product_Category__c='Appliance');
        Product2 productH = new Product2(Name='H', ProductCode='H', IsActive=true,Product_Category__c='Appliance');
        List<Product2> products = new List<Product2> { productA, productB, productC, productD, productE, productF, productG, productH };
            insert products;
        //productA.ReplaceableHDD__c = productB.Id;
        productB.RMA_Primary_Replacement__c = productC.Id;
        productB.RMA_Alternate_1__c = productD.Id;
        productB.RMA_Alternate_2__c = productE.Id;
        productA.RMA_Primary_Replacement__c = productF.Id;
        productA.RMA_Alternate_1__c = productG.Id;
        productA.RMA_Alternate_2__c = productH.Id;
        update products;
        
        //replaccement path should be C->D->E
        
        Account acc = new Account(Name='acme');
        insert acc;
        Contact ct = new Contact(LastName='acme', AccountId=acc.Id);
        insert ct;
        Asset assetX = new Asset(Name='acme', AccountId=acc.Id, ContactId=ct.Id, Product2Id=productA.Id);
        insert assetX;
        
        RMA__c rma = new RMA__c(Type__c='Return for Repair');
        insert rma;
        RMA_Item__c item = new RMA_Item__c(RMA__c=rma.Id, Type__c='Return - Repair and Return', Asset__c=assetX.Id, Product2__c=productC.Id, AltProdPreviouslyOrdered__c=productB.Id);
        insert item;
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('D', item.Product2__r.Name);
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('E', item.Product2__r.Name);
    }
    
    @isTest
    static void testChangeRMAItemProduct2()
    {
        Account spAccount= new Account(Name='Silver Peak Systems');
        insert spAccount;
        Product2 productA = new Product2(Name='A', ProductCode='A', IsActive=true,Product_Category__c='Appliance');
        Product2 productB = new Product2(Name='B', ProductCode='B', IsActive=true,Product_Category__c='Appliance');
        Product2 productC = new Product2(Name='C', ProductCode='C', IsActive=true,Product_Category__c='Appliance');
        Product2 productD = new Product2(Name='D', ProductCode='D', IsActive=true,Product_Category__c='Appliance');
        Product2 productE = new Product2(Name='E', ProductCode='E', IsActive=true,Product_Category__c='Appliance');
        Product2 productF = new Product2(Name='F', ProductCode='F', IsActive=true,Product_Category__c='Appliance');
        Product2 productG = new Product2(Name='G', ProductCode='G', IsActive=true,Product_Category__c='Appliance');
        Product2 productH = new Product2(Name='H', ProductCode='H', IsActive=true,Product_Category__c='Appliance');
        List<Product2> products = new List<Product2> { productA, productB, productC, productD, productE, productF, productG, productH };
            insert products;
        //productA.ReplaceableHDD__c = productB.Id;
        productB.Family = 'Accessory';
        productB.Use_System_Alternative__c = true;
        productB.RMA_Primary_Replacement__c = null;
        productB.RMA_Alternate_1__c = productD.Id;
        productB.RMA_Alternate_2__c = productE.Id;
        productA.RMA_Primary_Replacement__c = productF.Id;
        productA.RMA_Alternate_1__c = productG.Id;
        productA.RMA_Alternate_2__c = productH.Id;
        update products;
        
        //replaccement path should be B->F->G->H
        
        Account acc = new Account(Name='acme');
        insert acc;
        Contact ct = new Contact(LastName='acme', AccountId=acc.Id);
        insert ct;
        Asset assetX = new Asset(Name='acme', AccountId=acc.Id, ContactId=ct.Id, Product2Id=productA.Id);
        insert assetX;
        
        RMA__c rma = new RMA__c(Type__c='Return for Repair');
        insert rma;
        RMA_Item__c item = new RMA_Item__c(RMA__c=rma.Id, Type__c='Return - Repair and Return', Asset__c=assetX.Id, Product2__c=productB.Id);
        insert item;
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('F', item.Product2__r.Name);
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('G', item.Product2__r.Name);
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('H', item.Product2__r.Name);
    }
    
    @isTest
    static void testChangeRMAItemProduct3()
    {
        Account spAccount= new Account(Name='Silver Peak Systems');
        insert spAccount;
        Product2 productA = new Product2(Name='A', ProductCode='A', IsActive=true,Product_Category__c='Appliance');
        Product2 productB = new Product2(Name='B', ProductCode='B', IsActive=true,Product_Category__c='Appliance');
        Product2 productC = new Product2(Name='C', ProductCode='C', IsActive=true,Product_Category__c='Appliance');
        Product2 productD = new Product2(Name='D', ProductCode='D', IsActive=true,Product_Category__c='Appliance');
        Product2 productE = new Product2(Name='E', ProductCode='E', IsActive=true,Product_Category__c='Appliance');
        Product2 productF = new Product2(Name='F', ProductCode='F', IsActive=true,Product_Category__c='Appliance');
        Product2 productG = new Product2(Name='G', ProductCode='G', IsActive=true,Product_Category__c='Appliance');
        Product2 productH = new Product2(Name='H', ProductCode='H', IsActive=true,Product_Category__c='Appliance');
        List<Product2> products = new List<Product2> { productA, productB, productC, productD, productE, productF, productG, productH };
            insert products;
        //productA.ReplaceableHDD__c = productB.Id;
        productB.Family = 'Accessory';
        productB.Use_System_Alternative__c = true;
        productB.RMA_Primary_Replacement__c = productC.Id;
        productB.RMA_Alternate_1__c = productD.Id;
        productB.RMA_Alternate_2__c = productE.Id;
        productA.RMA_Primary_Replacement__c = null;
        productA.RMA_Alternate_1__c = productG.Id;
        productA.RMA_Alternate_2__c = productH.Id;
        update products;
        
        //replaccement path should be C->A->G->H
        
        Account acc = new Account(Name='acme');
        insert acc;
        Contact ct = new Contact(LastName='acme', AccountId=acc.Id);
        insert ct;
        Asset assetX = new Asset(Name='acme', AccountId=acc.Id, ContactId=ct.Id, Product2Id=productA.Id);
        insert assetX;
        
        RMA__c rma = new RMA__c(Type__c='Return for Repair');
        insert rma;
        RMA_Item__c item = new RMA_Item__c(RMA__c=rma.Id, Type__c='Return - Repair and Return', Asset__c=assetX.Id, Product2__c=productC.Id, AltProdPreviouslyOrdered__c=productB.Id);
        insert item;
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('A', item.Product2__r.Name);
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('G', item.Product2__r.Name);
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c = 'Insufficient QOH';
        update rma;
        item = [select Product2__r.Name from RMA_Item__c where Id=:item.Id limit 1];
        System.assertEquals('H', item.Product2__r.Name);
    }
      @isTest
    static void testAfterRMAItemReceived()
    {
        Id accountId = TestUtilities.createTestAccount();
        Account spAccount= new Account(Name='Silver Peak Systems');
        insert spAccount;
        Product2 testProduct = TestUtilities.createTestProduct();
        testProduct.Product_Category__c = 'Appliance';
        update testProduct;
        Asset testAsset = TestUtilities.createTestAsset(accountId, testProduct.Id);
        RMA__c testRMA = TestUtilities.createTestRMA(accountId, null, null);
        RMA_Item__c testRMAItem = TestUtilities.createTestRMAItem(testRma.Id, testAsset.Id, testProduct.Id);
        
        testRMAItem.Status__c = 'Received';
        update testRMAItem;
        
        testAsset = [select AccountId, Status from Asset where Id = :testAsset.Id];
        system.assertEquals('Silver Peak Inventory', testAsset.Status);
    }
}