objects/RMA__c.object
<CustomObject>
    <description>Basic RMA tracking. This is the RMA header and the details of the items associated with the RMA are in the RMA Details.</description>
    <fields>
        <fullName>Account_Manager_Email_1__c</fullName>
        <label>Account Manager Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t29BEAQ</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Case__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>RMA&apos;s</relationshipLabel>
        <relationshipName>R00N30000000t2CnEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Disposition_Notes__c</fullName>
        <label>Disposition Notes</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Disposition__c</fullName>
        <label>Disposition</label>
        <picklist>
            <picklistValues>
                <fullName>Return to Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Engineering</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Scrap</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ENG FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LANNER FA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NO FA REQUIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Note_Loc_1__c</fullName>
        <label>Note -Loc 1</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Initiated</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Logistics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Shipped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In FA/Recd</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dispatch Rejected</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>System_Engineer_Email_1__c</fullName>
        <label>System Engineer Email 1</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Tracking_Information__c</fullName>
        <inlineHelpText>Enter in format CARRIER:TRACKING NUMBERS</inlineHelpText>
        <label>Tracking Information</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return for Repair</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance Replace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Eval Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recall</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA</label>
    <nameField>
        <displayFormat>RMA-{YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA&apos;s</pluralLabel>
    <recordTypes>
        <fullName>RMA</fullName>
        <active>true</active>
        <description>Advance Replace, Repair and REcall RMAs</description>
        <label>RMA</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

objects/RMA_Item__c.object
<CustomObject>
    <description>RMA detail line items that track specific products to be shipped or returned to/from a customer location.</description>
    <fields>
        <fullName>Asset__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Asset</label>
        <referenceTo>Asset</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2EPEAY</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Product2__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Replacement Product</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>R00N30000000t2CyEAI</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RMA__c</fullName>
        <label>RMA</label>
        <referenceTo>RMA__c</referenceTo>
        <relationshipLabel>RMA Items</relationshipLabel>
        <relationshipName>RMALines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Dispatched</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Initiated</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RSM Assist</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Awaiting Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Received</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Return - Repair and Return</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Return - Refurbish and Stock</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Advance - Ship Unit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>RMA Item</label>
    <nameField>
        <displayFormat>RMA Item - {YYYY}{MM}{DD}-{0}</displayFormat>
        <label>RMA Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RMA Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/TestRMATriggerHandler.cls
@IsTest
public class TestRMATriggerHandler {
   @isTest
    static void TestUpdateRMACountOnCase()
    {
        Account acc = new Account(Name = 'acme');
        insert acc;
        Case theCase = new Case(Subject = 'acme', AccountId = acc.Id);
        insert theCase;
        Case altCase = new Case(Subject = 'acme1', AccountId = acc.Id);
        insert altCase;
        RMA__c theRma = new RMA__c(Case__c = theCase.Id, Account__c = acc.Id);
        insert theRma;
        theCase = [select Id, RMA_count__c from Case where Id = :theCase.Id limit 1];
        System.assertEquals(1, theCase.RMA_count__c); 
        delete theRma;
        theCase = [select Id, RMA_count__c from Case where Id = :theCase.Id limit 1];
        System.assertEquals(0, theCase.RMA_count__c);
        undelete theRma;
        theCase = [select Id, RMA_count__c from Case where Id = :theCase.Id limit 1];
        System.assertEquals(1, theCase.RMA_count__c);
        theRma.Case__c=altCase.Id;
        update theRMA;
        theCase = [select Id, RMA_count__c from Case where Id = :theCase.Id limit 1];
        System.assertEquals(0, theCase.RMA_count__c);
    }
    @IsTest
    public static void TestSendNotificationToHardwareEngineering()
    {
        Account acc = new Account(Name='acme', Type='Eval');
        insert acc;
        Account spAcc = new Account(Name='Silver Peak Systems');
        insert spAcc;
        Contact con = new Contact(LastName='acme', AccountId=acc.Id);
        con.MailingStreet='address1 \r\n address2';
        insert con;
        List<Product2> pros = new List<Product2> { 
            new Product2(Name='acme1', ProductCode='acme1'),
                new Product2(Name='acme2', ProductCode='acme2'),
                new Product2(Name='acme3', ProductCode='acme3') };
                    insert pros;
        Product2 pro = new Product2(Name='acme', ProductCode='acme', Model__c='acme', RMA_Primary_Replacement__c=pros[0].Id);
        insert pro;
        Asset asset = new Asset(Name='acme', SerialNumber='acme', Quantity=1.00, Status='Conditional PO', Product2Id=pro.Id, AccountId=acc.Id, ContactId=con.Id);
        insert asset;
        
        RMA__c rma = new RMA__c();
        rma.Status__c='Initiated';
        rma.Type__c='Advance Replace';
        rma.Account__c=acc.Id;
        insert rma;
        RMA_Item__c rmaItem = new RMA_Item__c();
        rmaItem.RMA__c=rma.id;
        rmaItem.Asset__c= asset.id;
        rmaItem.Product2__c= pro.id;
        rmaItem.Type__c='Advance Ship Unit';
        rmaItem.Status__c='Initiated';
        insert rmaItem;
        
        rma.Status__c='In FA/Recd';
        rma.Disposition__c='ENG FA';
        rma.Disposition_Notes__c='test';
        update rma;
        
    }
       @isTest
    static void TestCopyAccountTeamEmailOnRMA()
    {
        Account account = new Account(Name='acme');
        Account account2 = new Account(Name='acme2');        
        insert new Account[] { account, account2};
        Opportunity opp = new Opportunity(Name = 'acme', AccountId = account.Id, StageName = 'Discovery', CloseDate = system.today(), Amount = 100,Product_Type__c='Both');
        Opportunity opp2 = new Opportunity(Name = 'acme2', AccountId = account2.Id, StageName = 'Discovery', CloseDate = system.today(), Amount = 100,Product_Type__c='Both');        
        insert new Opportunity[] { opp, opp2 };        
        AccountTeamMember member = new AccountTeamMember(AccountId = account.Id, UserId = UserInfo.getUserId(), TeamMemberRole = 'Account Manager');        
        AccountTeamMember member2 = new AccountTeamMember(AccountId = account2.Id, UserId = UserInfo.getUserId(), TeamMemberRole = 'Systems Engineer');
        insert new AccountTeamMember[]{ member, member2 };                      
        RMA__c rma = new RMA__c(Account__c = account.Id);
        RMA__c rma2 = new RMA__c(Account__c = account2.Id);        
        insert new RMA__c[]{ rma, rma2 };       
        system.assertEquals(Userinfo.getUserEmail(), [SELECT Account_Manager_Email_1__c, System_Engineer_Email_1__c FROM RMA__c WHERE id = :rma.Id][0].Account_Manager_Email_1__c);
        system.assertEquals(Userinfo.getUserEmail(), [SELECT Account_Manager_Email_1__c, System_Engineer_Email_1__c FROM RMA__c WHERE id = :rma2.Id][0].System_Engineer_Email_1__c);        
        member.TeamMemberRole = 'Systems Engineer';
        update member;        
        update rma;
        system.assertEquals(Userinfo.getUserEmail(), [SELECT Account_Manager_Email_1__c, System_Engineer_Email_1__c FROM RMA__c WHERE id = :rma.Id][0].System_Engineer_Email_1__c);
    }
     @isTest
    static void TestUpdateRMATrackingInfoToCase()
    {
        Account acc = new Account(Name = 'acme');
        insert acc;
        Case theCase = new Case(Subject = 'acme', AccountId = acc.Id);
        insert theCase;
        RMA__c theRma = new RMA__c(Case__c = theCase.Id, Account__c = acc.Id, Tracking_Information__c='test');
        insert theRma;
        
        theCase = [select Id, RMATrackingInfo__c from Case where Id=:theCase.Id limit 1];
        System.assertEquals('test', theCase.RMATrackingInfo__c);
        
        theRma.Tracking_Information__c = 'acme';
        update theRma;
        theCase = [select Id, RMATrackingInfo__c from Case where Id=:theCase.Id limit 1];
        System.assertEquals('acme', theCase.RMATrackingInfo__c);
    }
    @isTest
    static void TestDispatchRMAItem()
    {
        Product2 productA = new Product2(Name='A', ProductCode='A', IsActive=true);
        insert productA;
        Account acc = new Account(Name='acme');
        insert acc;
        Account spAcc = new Account(Name='Silver Peak Systems');
        insert spAcc;
        Contact ct = new Contact(LastName='acme', AccountId=acc.Id);
        insert ct;
        Asset assetX = new Asset(Name='acme', AccountId=acc.Id, ContactId=ct.Id, Product2Id=productA.Id);
        insert assetX;
       
        RMA__c rma = new RMA__c(Type__c='Return for Repair');
        insert rma;
        RMA_Item__c item = new RMA_Item__c(RMA__c=rma.Id, Type__c='Return - Repair and Return', Asset__c=assetX.Id, Product2__c=productA.Id);
        insert item;
        
        rma.Status__c= 'Dispatched';
        update rma;
       
    }
    @isTest
    static void TestDispatchRejectedRMA()
    {
        Product2 productA = new Product2(Name='A', ProductCode='A', IsActive=true);
        insert productA;
        Account acc = new Account(Name='acme');
        insert acc;
        Account spAcc = new Account(Name='Silver Peak Systems');
        insert spAcc;
        Contact ct = new Contact(LastName='acme', AccountId=acc.Id);
        insert ct;
        Asset assetX = new Asset(Name='acme', AccountId=acc.Id, ContactId=ct.Id, Product2Id=productA.Id);
        insert assetX;
       
        RMA__c rma = new RMA__c(Type__c='Return for Repair');
        insert rma;
        RMA_Item__c item = new RMA_Item__c(RMA__c=rma.Id, Type__c='Return - Repair and Return', Asset__c=assetX.Id, Product2__c=productA.Id);
        insert item;
        
        rma.Status__c= 'Dispatch Rejected';
        rma.Note_Loc_1__c='Part Number Not Found';
        update rma;
       
    }
}